### ISSUE TITLE
[Processing Request]: CSLC-S1 Additional Product Request Over SAF

### ISSUE THREAD

**Issue by gracebato** [nasa/opera-sds#11]
### Venue

PST

### Product

CSLC-S1

### Input Data

=====================================================================================
Listing data for ASCENDING pass 137 from 2023-08-01 to 2023-09-16
=====================================================================================
S1A_IW_SLC__1SDV_20230910T015922_20230910T015949_050259_060CC8_356D
S1A_IW_SLC__1SDV_20230829T015922_20230829T015949_050084_0606D7_D5F0
S1A_IW_SLC__1SDV_20230817T015921_20230817T015948_049909_0600D7_5151
S1A_IW_SLC__1SDV_20230805T015921_20230805T015948_049734_05FAFD_4526

=====================================================================================
Listing data for DESCENDING pass 42 from 2023-08-01 to 2023-09-16
=====================================================================================
S1A_IW_SLC__1SDV_20230915T140836_20230915T140903_050339_060F86_2F8B
S1A_IW_SLC__1SDV_20230903T140836_20230903T140903_050164_06099B_C3B2
S1A_IW_SLC__1SDV_20230822T140835_20230822T140902_049989_06039A_9E8A
S1A_IW_SLC__1SDV_20230810T140833_20230810T140900_049814_05FD9D_67F9

### Share Results

- [ ] Google Earth Engine (GEE)
- [ ] NASA Distributed Active Archive Centers (DAAC) User Acceptance Testing (UAT)

### Additional Notes

No need to produce STATIC LAYERS.

**Comment by gracebato** [comment]
To keep burst_ids:

t042-088925-iw1
t137-292330-iw1
t137-292331-iw1
t137-292330-iw2'

**Comment by niarenaw** [comment]
Products have been generated and are available in s3 under the following URIs:
[cslc_outputs_20230917.txt](https://github.com/nasa/opera-sds/files/12644430/cslc_outputs_20230917.txt)

**Comment by riverma** [comment]
@gracebato - please add a title for this request after the string "Processing Request: ..." for easier communication. Thanks.
