### ISSUE TITLE
[Processing Request]: Missing dates for T137

### ISSUE THREAD

**Issue by gracebato** [nasa/opera-sds#15]
### Venue

PST

### Product

CSLC-S1

### Input Data

S1A_IW_SLC__1SDV_20220331T020155_20220331T020225_042559_05139C_26AC
S1A_IW_SLC__1SDV_20220319T020155_20220319T020225_042384_050DA6_E4FB
S1B_IW_SLC__1SDV_20211219T020106_20211219T020133_030088_0397B7_D854
S1B_IW_SLC__1SDV_20211207T020107_20211207T020134_029913_039228_F24F
S1B_IW_SLC__1SDV_20211125T020107_20211125T020134_029738_038CAA_8FDD
S1B_IW_SLC__1SDV_20211113T020108_20211113T020135_029563_03872D_8B24
S1B_IW_SLC__1SDV_20211101T020108_20211101T020135_029388_0381DB_44DE
S1B_IW_SLC__1SDV_20211020T020108_20211020T020135_029213_037C80_A383
S1B_IW_SLC__1SDV_20211008T020108_20211008T020135_029038_037708_B87B
S1B_IW_SLC__1SDV_20210926T020108_20210926T020135_028863_0371CC_461D
S1B_IW_SLC__1SDV_20210914T020107_20210914T020134_028688_036C6F_07DB
S1B_IW_SLC__1SDV_20210902T020107_20210902T020134_028513_036708_D155
S1B_IW_SLC__1SDV_20210821T020106_20210821T020133_028338_036195_F843
S1B_IW_SLC__1SDV_20210809T020106_20210809T020133_028163_035C1C_2528
S1B_IW_SLC__1SDV_20210728T020105_20210728T020132_027988_0356CA_052C
S1B_IW_SLC__1SDV_20210716T020104_20210716T020131_027813_0351A3_C34C
S1B_IW_SLC__1SDV_20210622T020103_20210622T020130_027463_034798_C281
S1B_IW_SLC__1SDV_20210610T020102_20210610T020129_027288_034264_28B7
S1B_IW_SLC__1SDV_20210529T020101_20210529T020128_027113_033D24_854B
S1B_IW_SLC__1SDV_20210517T020101_20210517T020128_026938_0337E4_3431
S1B_IW_SLC__1SDV_20210505T020100_20210505T020127_026763_03326A_9202
S1B_IW_SLC__1SDV_20210423T020100_20210423T020127_026588_032CD3_D00D
S1B_IW_SLC__1SDV_20210411T020059_20210411T020126_026413_032732_58D6
S1B_IW_SLC__1SDV_20210330T020059_20210330T020126_026238_0321A7_4DE5
S1B_IW_SLC__1SDV_20210318T020058_20210318T020125_026063_031C17_B9D1
S1B_IW_SLC__1SDV_20210306T020058_20210306T020125_025888_031671_3F66
S1B_IW_SLC__1SDV_20210222T020058_20210222T020125_025713_0310B9_2298
S1B_IW_SLC__1SDV_20210210T020059_20210210T020126_025538_030B05_F9DC
S1B_IW_SLC__1SDV_20210129T020059_20210129T020126_025363_030553_F82F
S1B_IW_SLC__1SDV_20210117T020100_20210117T020126_025188_02FFBE_2A2D
S1B_IW_SLC__1SDV_20210105T020100_20210105T020127_025013_02FA23_D783
S1B_IW_SLC__1SDV_20201224T020100_20201224T020127_024838_02F487_655D
S1B_IW_SLC__1SDV_20201212T020101_20201212T020128_024663_02EEDA_9C8F
S1B_IW_SLC__1SDV_20201130T020102_20201130T020129_024488_02E932_2256
S1B_IW_SLC__1SDV_20201118T020102_20201118T020129_024313_02E3A8_81C5
S1B_IW_SLC__1SDV_20201106T020102_20201106T020129_024138_02DE25_1184
S1B_IW_SLC__1SDV_20201025T020102_20201025T020129_023963_02D8BF_90CB
S1B_IW_SLC__1SDV_20201013T020102_20201013T020129_023788_02D342_0FB3
S1B_IW_SLC__1SDV_20201001T020102_20201001T020129_023613_02CDD5_2E96
S1B_IW_SLC__1SDV_20200919T020102_20200919T020129_023438_02C852_5C54
S1B_IW_SLC__1SDV_20200907T020102_20200907T020128_023263_02C2D8_1941
S1B_IW_SLC__1SDV_20200826T020101_20200826T020128_023088_02BD67_D3A9
S1B_IW_SLC__1SDV_20200814T020100_20200814T020127_022913_02B7E1_EB14
S1B_IW_SLC__1SDV_20200802T020100_20200802T020127_022738_02B27B_46A7
S1B_IW_SLC__1SDV_20200721T020059_20200721T020126_022563_02AD2F_79C2
S1B_IW_SLC__1SDV_20200709T020058_20200709T020125_022388_02A7DD_B239
S1B_IW_SLC__1SDV_20200627T020057_20200627T020124_022213_02A288_5EE1
S1B_IW_SLC__1SDV_20200615T020057_20200615T020124_022038_029D33_C23E
S1B_IW_SLC__1SDV_20200603T020056_20200603T020123_021863_0297F1_BDB5
S1B_IW_SLC__1SDV_20200522T020055_20200522T020122_021688_0292AF_EFD8
S1B_IW_SLC__1SDV_20200510T020055_20200510T020122_021513_028D8B_C656
S1B_IW_SLC__1SDV_20200428T020054_20200428T020121_021338_02880D_9070
S1B_IW_SLC__1SDV_20200416T020054_20200416T020120_021163_028289_CD42
S1B_IW_SLC__1SDV_20200404T020053_20200404T020120_020988_027CFF_7491
S1B_IW_SLC__1SDV_20200323T020053_20200323T020120_020813_027773_825E
S1B_IW_SLC__1SDV_20200311T020053_20200311T020120_020638_0271EE_2503
S1B_IW_SLC__1SDV_20200228T020052_20200228T020119_020463_026C5B_F2A9
S1B_IW_SLC__1SDV_20200216T020053_20200216T020120_020288_0266BF_65BC
S1B_IW_SLC__1SDV_20200204T020053_20200204T020120_020113_02611E_B34E
S1B_IW_SLC__1SDV_20200123T020053_20200123T020120_019938_025B72_8D46
S1B_IW_SLC__1SDV_20200111T020054_20200111T020121_019763_0255E0_60F7
S1B_IW_SLC__1SDV_20191230T020054_20191230T020121_019588_02504E_3D8B
S1B_IW_SLC__1SDV_20191218T020055_20191218T020122_019413_024AC0_1D66
S1B_IW_SLC__1SDV_20191206T020055_20191206T020122_019238_024529_41B1
S1B_IW_SLC__1SDV_20191124T020056_20191124T020123_019063_023F9C_7C82
S1B_IW_SLC__1SDV_20191112T020056_20191112T020123_018888_0239FC_413F
S1B_IW_SLC__1SDV_20191031T020056_20191031T020123_018713_023456_F0DB
S1B_IW_SLC__1SDV_20191019T020056_20191019T020123_018538_022EE0_A273
S1B_IW_SLC__1SDV_20191007T020056_20191007T020123_018363_022980_8BF2
S1B_IW_SLC__1SDV_20190925T020056_20190925T020123_018188_0223F8_B4F0
S1B_IW_SLC__1SDV_20190913T020055_20190913T020122_018013_021E94_43BD
S1B_IW_SLC__1SDV_20190901T020055_20190901T020122_017838_02191D_1F4F
S1B_IW_SLC__1SDV_20190820T020054_20190820T020121_017663_0213AD_CA73
S1B_IW_SLC__1SDV_20190808T020054_20190808T020120_017488_020E36_CAD8
S1B_IW_SLC__1SDV_20190727T020053_20190727T020120_017313_0208EF_139B
S1B_IW_SLC__1SDV_20190715T020052_20190715T020119_017138_0203D9_4683
S1B_IW_SLC__1SDV_20190703T020051_20190703T020118_016963_01FEAF_83D6
S1B_IW_SLC__1SDV_20190621T020051_20190621T020118_016788_01F984_5FBD
S1B_IW_SLC__1SDV_20190609T020050_20190609T020117_016613_01F44E_8B2C
S1B_IW_SLC__1SDV_20190528T020049_20190528T020116_016438_01EF17_8FB7
S1B_IW_SLC__1SDV_20190516T020049_20190516T020115_016263_01E9BA_E209
S1B_IW_SLC__1SDV_20190504T020048_20190504T020115_016088_01E434_6B6B
S1B_IW_SLC__1SDV_20190422T020047_20190422T020114_015913_01DE5A_6011
S1B_IW_SLC__1SDV_20190410T020047_20190410T020114_015738_01D891_4C9A
S1B_IW_SLC__1SDV_20190329T020047_20190329T020114_015563_01D2BF_92B9
S1B_IW_SLC__1SDV_20190317T020046_20190317T020113_015388_01CD08_E950
S1B_IW_SLC__1SDV_20190305T020046_20190305T020113_015213_01C75E_9E2D
S1B_IW_SLC__1SDV_20190221T020046_20190221T020113_015038_01C19A_CF7E
S1B_IW_SLC__1SDV_20190209T020047_20190209T020114_014863_01BBDC_75FF
S1B_IW_SLC__1SDV_20190128T020047_20190128T020114_014688_01B61C_E71D
S1B_IW_SLC__1SDV_20190116T020047_20190116T020114_014513_01B086_51DE
S1B_IW_SLC__1SDV_20190104T020048_20190104T020115_014338_01AADC_3340
S1B_IW_SLC__1SDV_20181223T020048_20181223T020115_014163_01A51C_D21E
S1B_IW_SLC__1SDV_20181211T020049_20181211T020115_013988_019F4E_D63A
S1B_IW_SLC__1SDV_20181129T020049_20181129T020116_013813_0199A6_1750
S1B_IW_SLC__1SDV_20181117T020049_20181117T020116_013638_01940C_3089
S1B_IW_SLC__1SDV_20181105T020050_20181105T020117_013463_018E93_F977
S1B_IW_SLC__1SDV_20181024T020050_20181024T020117_013288_018910_6868
S1B_IW_SLC__1SDV_20181012T020050_20181012T020117_013113_0183A7_0379
S1B_IW_SLC__1SDV_20180930T020049_20180930T020116_012938_017E58_8279
S1B_IW_SLC__1SDV_20180918T020049_20180918T020116_012763_0178FA_6391
S1B_IW_SLC__1SDV_20180906T020049_20180906T020116_012588_01739D_338D
S1B_IW_SLC__1SDV_20180825T020048_20180825T020115_012413_016E33_85D0
S1B_IW_SLC__1SDV_20180813T020047_20180813T020114_012238_0168C9_BAF0
S1B_IW_SLC__1SDV_20180801T020047_20180801T020114_012063_016365_0E16
S1B_IW_SLC__1SDV_20180720T020046_20180720T020113_011888_015E1C_A7F2
S1B_IW_SLC__1SDV_20180708T020045_20180708T020112_011713_0158BE_7E38
S1B_IW_SLC__1SDV_20180602T020043_20180602T020110_011188_014879_5344
S1B_IW_SLC__1SDV_20180521T020042_20180521T020109_011013_0142CF_5756
S1B_IW_SLC__1SDV_20180427T020041_20180427T020108_010663_01377C_1B8F
S1B_IW_SLC__1SDV_20180403T020040_20180403T020107_010313_012C48_0A75
S1B_IW_SLC__1SDV_20180310T020040_20180310T020107_009963_0120E8_5280
S1B_IW_SLC__1SDV_20180226T020040_20180226T020107_009788_011B09_235D
S1B_IW_SLC__1SDV_20180109T020041_20180109T020108_009088_01040D_B240
S1B_IW_SLC__1SDV_20171228T020041_20171228T020108_008913_00FE5B_FDAB
S1B_IW_SLC__1SDV_20171204T020042_20171204T020109_008563_00F32F_5161
S1B_IW_SLC__1SDV_20171110T020043_20171110T020110_008213_00E856_FAFF
S1B_IW_SLC__1SDV_20171017T020049_20171017T020111_007863_00DE2F_558C
S1B_IW_SLC__1SDV_20170911T020042_20170911T020109_007338_00CF24_6226
S1B_IW_SLC__1SDV_20170818T020041_20170818T020108_006988_00C4F5_2ABF
S1B_IW_SLC__1SDV_20170806T020041_20170806T020107_006813_00BFD7_3A51

### Share Results

- [ ] Google Earth Engine (GEE)
- [ ] NASA Distributed Active Archive Centers (DAAC) User Acceptance Testing (UAT)

### Additional Notes

These are the granule_ids related to the missing dates for T137 over Oregon.

**Comment by niarenaw** [comment]
Processing has completed. There are 3267 new products generated on 20230920, but I see the same set of products processed 
on 20230907. Are those the expected products that were thoguht to be missing? Both products are included in list below. 

[request15_s3_manifest.txt](https://github.com/nasa/opera-sds/files/12679706/request15_s3_manifest.txt)

**Comment by niarenaw** [comment]
So that s3 URI is a prefix for all the output products. `aws s3 cp` only works on individual objects. Using `aws s3 sync` instead should fix it.
