### ISSUE TITLE
[Processing Request]: Amazon, Descending, High Priority 

### ISSUE THREAD

**Issue by Alex-Lewandowski** [nasa/opera-sds#17]
### Venue

PST

### Product

RTC-S1

### SAS Version

latest

### SDS Version

latest

### Input Data

S1A_IW_SLC__1SDV_20210621T092215_20210621T092243_038436_04891A_DA41, S1A_IW_SLC__1SDV_20210609T092214_20210609T092242_038261_0483DE_0E07, S1A_IW_SLC__1SDV_20210528T092214_20210528T092242_038086_047EB2_5BE8, S1A_IW_SLC__1SDV_20210516T092213_20210516T092241_037911_047968_C84C, S1A_IW_SLC__1SDV_20210504T092212_20210504T092240_037736_047418_5DBF, S1A_IW_SLC__1SDV_20210422T092212_20210422T092240_037561_046DFE_7E8E, S1A_IW_SLC__1SDV_20210410T092211_20210410T092239_037386_0467EB_6EFE, S1A_IW_SLC__1SDV_20210329T092211_20210329T092239_037211_0461E3_175C, S1A_IW_SLC__1SDV_20210317T092211_20210317T092239_037036_045BDB_B281, S1A_IW_SLC__1SDV_20210305T092211_20210305T092239_036861_0455B7_C15C, S1A_IW_SLC__1SDV_20210221T092211_20210221T092239_036686_044FAC_7D24, S1A_IW_SLC__1SDV_20210209T092211_20210209T092239_036511_04498C_CB76, S1A_IW_SLC__1SDV_20210128T092211_20210128T092239_036336_04437D_306A, S1A_IW_SLC__1SDV_20210116T092212_20210116T092240_036161_043D65_1A22, S1A_IW_SLC__1SDV_20210104T092212_20210104T092240_035986_043740_618C

### Share Results

- [ ] Google Earth Engine (GEE)
- [ ] NASA Distributed Active Archive Centers (DAAC) User Acceptance Testing (UAT)

### Additional Notes

Scene for static file processing:
S1A_IW_SLC__1SDV_20210621T092215_20210621T092243_038436_04891A_DA41

**Comment by niarenaw** [comment]
[issue17_rtc.txt](https://github.com/nasa/opera-sds/files/12877050/issue17_rtc.txt)
