### ISSUE TITLE
[Processing Request]: Delta Junction, Ascending, High Priority

### ISSUE THREAD

**Issue by Alex-Lewandowski** [nasa/opera-sds#18]
### Venue

PST

### Product

RTC-S1

### SAS Version

latest

### SDS Version

latest

### Input Data

S1B_IW_SLC__1SDV_20211216T032012_20211216T032039_030045_039655_51BA, S1B_IW_SLC__1SDV_20211204T032013_20211204T032040_029870_0390CC_16BC, S1B_IW_SLC__1SDV_20211122T032013_20211122T032040_029695_038B4D_30A9, S1B_IW_SLC__1SDV_20211110T032013_20211110T032040_029520_0385E6_D859, S1B_IW_SLC__1SDV_20211029T032014_20211029T032041_029345_038088_54E9, S1B_IW_SLC__1SDV_20211017T032014_20211017T032041_029170_037B25_0BC6, S1B_IW_SLC__1SDV_20211005T032014_20211005T032041_028995_0375BC_FFDB, S1B_IW_SLC__1SDV_20210923T032013_20210923T032040_028820_037079_41C1, S1B_IW_SLC__1SDV_20210911T032013_20210911T032040_028645_036B22_076C, S1B_IW_SLC__1SDV_20210830T032012_20210830T032039_028470_0365B5_1FD4, S1B_IW_SLC__1SDV_20210818T032012_20210818T032039_028295_03603B_B0AE, S1B_IW_SLC__1SDV_20210806T032011_20210806T032038_028120_035AC2_01F6, S1B_IW_SLC__1SDV_20210725T032011_20210725T032038_027945_03558F_4350, S1B_IW_SLC__1SDV_20210713T032010_20210713T032037_027770_03505F_2184, S1B_IW_SLC__1SDV_20210701T032009_20210701T032036_027595_034B39_B844, S1B_IW_SLC__1SDV_20210619T032008_20210619T032035_027420_034657_9E49, S1B_IW_SLC__1SDV_20210607T032008_20210607T032035_027245_03411A_4226, S1B_IW_SLC__1SDV_20210526T032007_20210526T032034_027070_033BE4_A431, S1B_IW_SLC__1SDV_20210514T032006_20210514T032033_026895_033689_B26E, S1B_IW_SLC__1SDV_20210502T032006_20210502T032033_026720_03310E_C904, S1B_IW_SLC__1SDV_20210420T032005_20210420T032032_026545_032B75_399D, S1B_IW_SLC__1SDV_20210408T032005_20210408T032032_026370_0325D4_0831, S1B_IW_SLC__1SDV_20210327T032004_20210327T032031_026195_032049_E400, S1B_IW_SLC__1SDV_20210315T032004_20210315T032031_026020_031ABA_0FBA, S1B_IW_SLC__1SDV_20210303T032004_20210303T032031_025845_03150D_47A0, S1B_IW_SLC__1SDV_20210219T032004_20210219T032031_025670_030F52_E6E7, S1B_IW_SLC__1SDV_20210207T032004_20210207T032031_025495_03099C_AC1E, S1B_IW_SLC__1SDV_20210126T032005_20210126T032032_025320_0303F3_A06F, S1B_IW_SLC__1SDV_20210114T032005_20210114T032032_025145_02FE61_D2BD, S1B_IW_SLC__1SDV_20210102T032006_20210102T032033_024970_02F8C3_92DD, S1B_IW_SLC__1SDV_20201221T032006_20201221T032033_024795_02F320_8DF4, S1B_IW_SLC__1SDV_20201209T032007_20201209T032034_024620_02ED72_EB34, S1B_IW_SLC__1SDV_20201127T032007_20201127T032034_024445_02E7D2_0678, S1B_IW_SLC__1SDV_20201115T032008_20201115T032035_024270_02E254_9534, S1B_IW_SLC__1SDV_20201103T032008_20201103T032035_024095_02DCD3_6F3D, S1B_IW_SLC__1SDV_20201010T032008_20201010T032035_023745_02D1EB_CAE8, S1B_IW_SLC__1SDV_20200928T032008_20200928T032035_023570_02CC7F_D35D, S1B_IW_SLC__1SDV_20200916T032007_20200916T032034_023395_02C704_BC3C, S1B_IW_SLC__1SDV_20200904T032007_20200904T032034_023220_02C183_4881, S1B_IW_SLC__1SDV_20200823T032006_20200823T032033_023045_02BC13_AB65, S1B_IW_SLC__1SDV_20200811T032006_20200811T032033_022870_02B695_1362, S1B_IW_SLC__1SDV_20200730T032005_20200730T032032_022695_02B12E_86DF, S1B_IW_SLC__1SDV_20200718T032004_20200718T032031_022520_02ABDA_121E, S1B_IW_SLC__1SDV_20200706T032003_20200706T032030_022345_02A68E_C3EF, S1B_IW_SLC__1SDV_20200624T032003_20200624T032030_022170_02A137_5360, S1B_IW_SLC__1SDV_20200612T032002_20200612T032029_021995_029BE3_D41A, S1B_IW_SLC__1SDV_20200531T032002_20200531T032029_021820_0296A9_F207, S1B_IW_SLC__1SDV_20200519T032001_20200519T032027_021645_029171_0DC3, S1B_IW_SLC__1SDV_20200507T032000_20200507T032026_021470_028C3D_3C2C, S1B_IW_SLC__1SDV_20200425T031959_20200425T032026_021295_0286B6_FDB7, S1B_IW_SLC__1SDV_20200413T031959_20200413T032026_021120_028131_55DA, S1B_IW_SLC__1SDV_20200401T031959_20200401T032026_020945_027BA5_B74F, S1B_IW_SLC__1SDV_20200320T031958_20200320T032025_020770_02761F_AA8C, S1B_IW_SLC__1SDV_20200308T031958_20200308T032025_020595_027094_E254, S1B_IW_SLC__1SDV_20200225T031958_20200225T032025_020420_026B00_002B, S1B_IW_SLC__1SDV_20200213T031958_20200213T032025_020245_026562_D56E, S1B_IW_SLC__1SDV_20200201T031959_20200201T032026_020070_025FBA_01F6, S1B_IW_SLC__1SDV_20200120T031959_20200120T032026_019895_025A16_8B91, S1B_IW_SLC__1SDV_20200108T031959_20200108T032026_019720_025483_0D57, S1B_IW_SLC__1SDV_20191227T032000_20191227T032027_019545_024EF2_4B2D, S1B_IW_SLC__1SDV_20191215T032001_20191215T032027_019370_024962_F5E7, S1B_IW_SLC__1SDV_20191203T032001_20191203T032028_019195_0243D3_B74B, S1B_IW_SLC__1SDV_20191121T032001_20191121T032028_019020_023E42_F88A, S1B_IW_SLC__1SDV_20191109T032002_20191109T032029_018845_0238A0_3A5A, S1B_IW_SLC__1SDV_20191028T032002_20191028T032029_018670_0232F4_DE07, S1B_IW_SLC__1SDV_20191016T032002_20191016T032029_018495_022D93_F0F6, S1B_IW_SLC__1SDV_20191004T032002_20191004T032029_018320_022828_A72B, S1B_IW_SLC__1SDV_20190922T032001_20190922T032028_018145_0222B1_5F20, S1B_IW_SLC__1SDV_20190910T032001_20190910T032028_017970_021D4C_D5B0, S1B_IW_SLC__1SDV_20190829T032000_20190829T032027_017795_0217CD_C428, S1B_IW_SLC__1SDV_20190817T032000_20190817T032027_017620_02125D_FCA3, S1B_IW_SLC__1SDV_20190805T031959_20190805T032025_017445_020CF4_E6A4, S1B_IW_SLC__1SDV_20190724T031958_20190724T032024_017270_0207AF_AA74, S1B_IW_SLC__1SDV_20190712T031957_20190712T032024_017095_02029A_9011, S1B_IW_SLC__1SDV_20190630T031957_20190630T032023_016920_01FD74_4219, S1B_IW_SLC__1SDV_20190618T031956_20190618T032022_016745_01F845_5AC5, S1B_IW_SLC__1SDV_20190606T031955_20190606T032021_016570_01F312_42ED, S1B_IW_SLC__1SDV_20190525T031955_20190525T032021_016395_01EDD0_EEC3, S1B_IW_SLC__1SDV_20190513T031954_20190513T032020_016220_01E867_FD16, S1B_IW_SLC__1SDV_20190501T031954_20190501T032021_016045_01E2C8_3F80, S1B_IW_SLC__1SDV_20190419T031953_20190419T032020_015870_01DCEE_2286, S1B_IW_SLC__1SDV_20190407T031953_20190407T032019_015695_01D725_4A09, S1B_IW_SLC__1SDV_20190326T031952_20190326T032019_015520_01D15C_658E, S1B_IW_SLC__1SDV_20190314T031952_20190314T032019_015345_01CBA5_A4DE, S1B_IW_SLC__1SDV_20190302T031952_20190302T032019_015170_01C5EA_0FC6, S1B_IW_SLC__1SDV_20190218T031952_20190218T032019_014995_01C032_B1D0, S1B_IW_SLC__1SDV_20190206T031952_20190206T032019_014820_01BA73_3090, S1B_IW_SLC__1SDV_20190125T031953_20190125T032020_014645_01B4B4_B0CE, S1B_IW_SLC__1SDV_20190113T031953_20190113T032020_014470_01AF1D_658B, S1B_IW_SLC__1SDV_20190101T031953_20190101T032020_014295_01A97B_0842, S1B_IW_SLC__1SDV_20181220T031954_20181220T032021_014120_01A3AB_FED2, S1B_IW_SLC__1SDV_20181208T031954_20181208T032021_013945_019DEF_B96C, S1B_IW_SLC__1SDV_20181114T031955_20181114T032022_013595_0192AE_6D02, S1B_IW_SLC__1SDV_20181102T031955_20181102T032022_013420_018D40_C6E5, S1B_IW_SLC__1SDV_20181021T031955_20181021T032022_013245_0187C1_CCC4, S1B_IW_SLC__1SDV_20181009T031955_20181009T032022_013070_018259_0739, S1B_IW_SLC__1SDV_20180915T031955_20180915T032022_012720_01779E_CC4A, S1B_IW_SLC__1SDV_20180903T031954_20180903T032021_012545_017248_BB82, S1B_IW_SLC__1SDV_20180822T031954_20180822T032021_012370_016CDD_2D13, S1B_IW_SLC__1SDV_20180810T031953_20180810T032020_012195_01676D_4396, S1B_IW_SLC__1SDV_20180729T031952_20180729T032019_012020_016211_A97B, S1B_IW_SLC__1SDV_20180717T031951_20180717T032018_011845_015CCE_8ADE, S1B_IW_SLC__1SDV_20180705T031951_20180705T032018_011670_015769_766D, S1B_IW_SLC__1SDV_20180623T031950_20180623T032017_011495_0151F5_D471, S1B_IW_SLC__1SDV_20180611T031949_20180611T032016_011320_014C8D_38A3, S1B_IW_SLC__1SDV_20180530T031948_20180530T032015_011145_014714_72CD, S1B_IW_SLC__1SDV_20180518T031948_20180518T032015_010970_014156_4425, S1B_IW_SLC__1SDV_20180506T031947_20180506T032014_010795_013BB3_5F97, S1B_IW_SLC__1SDV_20180424T031947_20180424T032014_010620_013610_1A19, S1B_IW_SLC__1SDV_20180412T031946_20180412T032013_010445_01307C_9A8B, S1B_IW_SLC__1SDV_20180331T031946_20180331T032013_010270_012ACC_05CE, S1B_IW_SLC__1SDV_20180319T031945_20180319T032012_010095_012522_F36B, S1B_IW_SLC__1SDV_20180307T031945_20180307T032012_009920_011F6A_5CA9, S1B_IW_SLC__1SDV_20180223T031945_20180223T032012_009745_011990_6CA3, S1B_IW_SLC__1SDV_20180211T031946_20180211T032013_009570_0113CE_56AB, S1B_IW_SLC__1SDV_20180118T031946_20180118T032013_009220_01084D_3730, S1B_IW_SLC__1SDV_20180106T031946_20180106T032013_009045_01029C_E9A7, S1B_IW_SLC__1SDV_20171213T031948_20171213T032014_008695_00F752_7973, S1B_IW_SLC__1SDV_20171201T031948_20171201T032015_008520_00F1C6_E693, S1B_IW_SLC__1SDV_20171107T031948_20171107T032015_008170_00E708_86F1, S1B_IW_SLC__1SDV_20171002T031948_20171002T032015_007645_00D7FD_3825, S1B_IW_SLC__1SDV_20170920T031948_20170920T032015_007470_00D2FC_EE0A, S1B_IW_SLC__1SDV_20170908T031947_20170908T032014_007295_00CDDC_9760, S1B_IW_SLC__1SDV_20170827T031947_20170827T032014_007120_00C8C4_677E, S1B_IW_SLC__1SDV_20170815T031946_20170815T032013_006945_00C3B3_3196, S1B_IW_SLC__1SDV_20170722T031945_20170722T032012_006595_00B992_8781, S1B_IW_SLC__1SDV_20170710T031945_20170710T032011_006420_00B491_1450, S1B_IW_SLC__1SDV_20170628T031944_20170628T032011_006245_00AFA2_633D, S1B_IW_SLC__1SDV_20170616T031943_20170616T032010_006070_00AA8F_CB55, S1B_IW_SLC__1SDV_20170604T031942_20170604T032009_005895_00A568_0E38, S1B_IW_SLC__1SDV_20170523T031942_20170523T032009_005720_00A055_95C3, S1B_IW_SLC__1SDV_20170511T031941_20170511T032008_005545_009B64_A39D, S1B_IW_SLC__1SDV_20170429T031940_20170429T032007_005370_009693_955E, S1B_IW_SLC__1SDV_20170417T031940_20170417T032007_005195_009174_114E, S1B_IW_SLC__1SDV_20170405T031939_20170405T032006_005020_008C75_06A5, S1B_IW_SLC__1SDV_20170324T031939_20170324T032006_004845_008766_120F, S1B_IW_SLC__1SDV_20170312T031939_20170312T032006_004670_008251_DD9F, S1B_IW_SLC__1SDV_20170228T031939_20170228T032005_004495_007D2E_E78F, S1B_IW_SLC__1SDV_20170204T031939_20170204T032006_004145_0072BE_DA33, S1B_IW_SLC__1SDV_20170111T031940_20170111T032007_003795_00685F_3EC6, S1B_IW_SLC__1SDV_20161218T031941_20161218T032008_003445_005E27_D5A9, S1B_IW_SLC__1SDV_20161124T031942_20161124T032009_003095_005430_36D7, S1B_IW_SLC__1SSV_20161031T031943_20161031T032010_002745_004A59_C312, S1A_IW_SLC__1SDV_20160814T032023_20160814T032050_012591_013BCA_88E4, S1A_IW_SLC__1SSV_20160510T032018_20160510T032045_011191_010E78_3C3B, S1A_IW_SLC__1SSV_20160416T032016_20160416T032043_010841_010387_691C, S1A_IW_SLC__1SSV_20160323T032015_20160323T032042_010491_00F931_350A, S1A_IW_SLC__1SSV_20160204T032015_20160204T032042_009791_00E521_D10F, S1A_IW_SLC__1SSV_20160111T032016_20160111T032043_009441_00DAF0_C546, S1A_IW_SLC__1SDV_20151218T032017_20151218T032043_009091_00D0EE_41C3, S1A_IW_SLC__1SSV_20151124T032017_20151124T032044_008741_00C72B_8825

### Share Results

- [ ] Google Earth Engine (GEE)
- [ ] NASA Distributed Active Archive Centers (DAAC) User Acceptance Testing (UAT)

### Additional Notes

Scene for static processing:
S1B_IW_SLC__1SDV_20211216T032012_20211216T032039_030045_039655_51BA

**Comment by niarenaw** [comment]
outputs: [issue18_rtc.txt](https://github.com/nasa/opera-sds/files/12877052/issue18_rtc.txt)
