### ISSUE TITLE
[Processing Request]: Delta Junction, Descending, High Priority

### ISSUE THREAD

**Issue by Alex-Lewandowski** [nasa/opera-sds#19]
### Venue

PST

### Product

RTC-S1

### SAS Version

latest

### SDS Version

latest

### Input Data

S1A_IW_SLC__1SDV_20230713T161236_20230713T161303_049407_05F0ED_B461, S1A_IW_SLC__1SDV_20230701T161235_20230701T161302_049232_05EB7F_A885, S1A_IW_SLC__1SDV_20230619T161234_20230619T161301_049057_05E635_16DF, S1A_IW_SLC__1SDV_20230607T161233_20230607T161300_048882_05E0DC_17E5, S1A_IW_SLC__1SDV_20230502T161232_20230502T161259_048357_05D0E9_AC8D, S1A_IW_SLC__1SDV_20230420T161231_20230420T161257_048182_05CB04_1A8D, S1A_IW_SLC__1SDV_20230408T161231_20230408T161258_048007_05C527_B468, S1A_IW_SLC__1SDV_20230327T161230_20230327T161257_047832_05BF3F_9487, S1A_IW_SLC__1SDV_20230315T161230_20230315T161257_047657_05B95A_C4FC, S1A_IW_SLC__1SDV_20230303T161230_20230303T161257_047482_05B36B_8B1F, S1A_IW_SLC__1SDV_20230219T161230_20230219T161257_047307_05AD81_CEB4, S1A_IW_SLC__1SDV_20230207T161230_20230207T161257_047132_05A798_7446, S1A_IW_SLC__1SDV_20230126T161231_20230126T161258_046957_05A1BF_1BA1, S1A_IW_SLC__1SDV_20230114T161231_20230114T161258_046782_059BD6_D15F, S1A_IW_SLC__1SDV_20230102T161232_20230102T161259_046607_0595F6_E3D9, S1A_IW_SLC__1SDV_20221221T161232_20221221T161259_046432_05900A_E6D4, S1A_IW_SLC__1SDV_20221209T161233_20221209T161300_046257_058A0C_20C7, S1A_IW_SLC__1SDV_20221127T161234_20221127T161301_046082_058411_866F, S1A_IW_SLC__1SDV_20221115T161234_20221115T161301_045907_057E27_C2B0, S1A_IW_SLC__1SDV_20221103T161234_20221103T161301_045732_057837_A7C1, S1A_IW_SLC__1SDV_20221022T161234_20221022T161301_045557_057253_D8E9, S1A_IW_SLC__1SDV_20221010T161234_20221010T161301_045382_056D26_B194, S1A_IW_SLC__1SDV_20220928T161234_20220928T161301_045207_056743_FBFD, S1A_IW_SLC__1SDV_20220916T161234_20220916T161301_045032_056166_629E, S1A_IW_SLC__1SDV_20220904T161234_20220904T161301_044857_055B87_C391, S1A_IW_SLC__1SDV_20220823T161233_20220823T161300_044682_05559F_60DB, S1A_IW_SLC__1SDV_20220811T161232_20220811T161259_044507_054FB0_D835, S1A_IW_SLC__1SDV_20220624T161230_20220624T161257_043807_053AD3_F725, S1A_IW_SLC__1SDV_20220507T161226_20220507T161253_043107_0525DC_225F, S1A_IW_SLC__1SDV_20220413T161225_20220413T161252_042757_051A4A_9180, S1A_IW_SLC__1SDV_20220320T161224_20220320T161251_042407_050E72_87ED, S1A_IW_SLC__1SDV_20220308T161224_20220308T161251_042232_050885_AE3E, S1A_IW_SLC__1SDV_20220224T161224_20220224T161251_042057_050291_30C2, S1A_IW_SLC__1SDV_20220212T161225_20220212T161251_041882_04FC7B_537D, S1A_IW_SLC__1SDV_20220131T161225_20220131T161252_041707_04F66E_BEBE, S1A_IW_SLC__1SDV_20220119T161225_20220119T161252_041532_04F075_6ADA, S1A_IW_SLC__1SDV_20220107T161226_20220107T161253_041357_04EABD_37C6, S1A_IW_SLC__1SDV_20211226T161226_20211226T161253_041182_04E4C4_195D, S1A_IW_SLC__1SDV_20211214T161227_20211214T161254_041007_04DF04_1C30, S1A_IW_SLC__1SDV_20211202T161227_20211202T161254_040832_04D8FA_1467, S1A_IW_SLC__1SDV_20211120T161228_20211120T161255_040657_04D2DF_0D40, S1A_IW_SLC__1SDV_20211108T161228_20211108T161255_040482_04CCDD_F287, S1A_IW_SLC__1SDV_20211027T161228_20211027T161255_040307_04C6C2_080A, S1A_IW_SLC__1SDV_20211015T161228_20211015T161255_040132_04C0A5_04BB, S1A_IW_SLC__1SDV_20211003T161228_20211003T161255_039957_04BA9A_E30E, S1A_IW_SLC__1SDV_20210921T161228_20210921T161255_039782_04B48D_0DC1, S1A_IW_SLC__1SDV_20210828T161227_20210828T161254_039432_04A884_FF6B, S1A_IW_SLC__1SDV_20210804T161226_20210804T161253_039082_049C8E_36C6, S1A_IW_SLC__1SDV_20210524T161221_20210524T161248_038032_047D1D_305B, S1A_IW_SLC__1SDV_20210512T161221_20210512T161248_037857_0477D6_AEAF, S1A_IW_SLC__1SDV_20210430T161220_20210430T161247_037682_047233_C40D, S1A_IW_SLC__1SDV_20210418T161220_20210418T161247_037507_046C21_34DA, S1A_IW_SLC__1SDV_20210406T161219_20210406T161246_037332_046613_8A57, S1A_IW_SLC__1SDV_20210325T161219_20210325T161246_037157_046003_8A5B, S1A_IW_SLC__1SDV_20210313T161219_20210313T161246_036982_0459FB_6EE0, S1A_IW_SLC__1SDV_20210301T161219_20210301T161246_036807_0453DA_543F, S1A_IW_SLC__1SDV_20210217T161219_20210217T161246_036632_044DCF_931D, S1A_IW_SLC__1SDV_20210205T161219_20210205T161246_036457_0447A9_53E4, S1A_IW_SLC__1SDV_20210124T161219_20210124T161246_036282_04419B_6F63, S1A_IW_SLC__1SDV_20210112T161220_20210112T161247_036107_043B8E_67EF, S1A_IW_SLC__1SDV_20201231T161221_20201231T161247_035932_043566_9777, S1A_IW_SLC__1SDV_20201219T161221_20201219T161248_035757_042F4D_CD11, S1A_IW_SLC__1SDV_20201207T161222_20201207T161249_035582_042947_B620, S1A_IW_SLC__1SDV_20201125T161222_20201125T161249_035407_042340_7498, S1A_IW_SLC__1SDV_20201113T161222_20201113T161249_035232_041D38_F655, S1A_IW_SLC__1SDV_20201101T161223_20201101T161250_035057_041716_9A10, S1A_IW_SLC__1SDV_20201020T161223_20201020T161250_034882_041126_B2D2, S1A_IW_SLC__1SDV_20201008T161223_20201008T161250_034707_040AFA_EDF2, S1A_IW_SLC__1SDV_20200926T161222_20200926T161249_034532_0404DE_CEDD, S1A_IW_SLC__1SDV_20200914T161222_20200914T161249_034357_03FEB7_6D09, S1A_IW_SLC__1SDV_20200902T161222_20200902T161248_034182_03F892_6EAC, S1A_IW_SLC__1SDV_20200821T161221_20200821T161248_034007_03F266_DDC7, S1A_IW_SLC__1SDV_20200809T161220_20200809T161247_033832_03EC40_1C24, S1A_IW_SLC__1SDV_20200716T161219_20200716T161246_033482_03E13C_B9B7, S1A_IW_SLC__1SDV_20200704T161218_20200704T161245_033307_03DBE4_E191, S1A_IW_SLC__1SDV_20200622T161217_20200622T161244_033132_03D696_EF40, S1A_IW_SLC__1SDV_20200610T161217_20200610T161244_032957_03D145_A962, S1A_IW_SLC__1SDV_20200529T161216_20200529T161243_032782_03CC1C_9C71, S1A_IW_SLC__1SDV_20200505T161214_20200505T161241_032432_03C17C_6635, S1A_IW_SLC__1SDV_20200423T161214_20200423T161241_032257_03BB4D_C693, S1A_IW_SLC__1SDV_20200411T161213_20200411T161240_032082_03B52A_D3AC, S1A_IW_SLC__1SDV_20200330T161213_20200330T161240_031907_03AEFE_0E6B, S1A_IW_SLC__1SDV_20200318T161213_20200318T161240_031732_03A8D7_1ABB, S1A_IW_SLC__1SDV_20200306T161213_20200306T161240_031557_03A2C3_55DC, S1A_IW_SLC__1SDV_20200223T161213_20200223T161240_031382_039CB7_692D, S1A_IW_SLC__1SDV_20200211T161213_20200211T161240_031207_0396AE_B345, S1A_IW_SLC__1SDV_20200130T161213_20200130T161240_031032_039096_40CE, S1A_IW_SLC__1SDV_20200118T161214_20200118T161241_030857_038A73_DB38, S1A_IW_SLC__1SDV_20191225T161215_20191225T161242_030507_037E49_36B7, S1A_IW_SLC__1SDV_20191213T161215_20191213T161242_030332_03783E_6EAA, S1A_IW_SLC__1SDV_20191201T161216_20191201T161242_030157_037230_D4FE, S1A_IW_SLC__1SDV_20191119T161216_20191119T161243_029982_036C1F_16AC, S1A_IW_SLC__1SDV_20191107T161216_20191107T161243_029807_036610_0808, S1A_IW_SLC__1SDV_20191026T161216_20191026T161243_029632_035FDF_FD8A, S1A_IW_SLC__1SDV_20191014T161216_20191014T161243_029457_0359E0_DA14, S1A_IW_SLC__1SDV_20191002T161216_20191002T161243_029282_0353D3_71E0, S1A_IW_SLC__1SDV_20190920T161216_20190920T161243_029107_034DD0_FE28, S1A_IW_SLC__1SDV_20190908T161215_20190908T161242_028932_0347C5_279C, S1A_IW_SLC__1SDV_20190827T161215_20190827T161242_028757_0341B4_FB03, S1A_IW_SLC__1SDV_20190815T161214_20190815T161241_028582_033B9B_1BD7, S1A_IW_SLC__1SDV_20190429T161208_20190429T161235_027007_030A75_C43E, S1A_IW_SLC__1SDV_20190417T161207_20190417T161234_026832_030424_D8BB, S1A_IW_SLC__1SDV_20190405T161207_20190405T161234_026657_02FDC5_95E6, S1A_IW_SLC__1SDV_20190324T161207_20190324T161234_026482_02F74E_2887, S1A_IW_SLC__1SDV_20190312T161207_20190312T161233_026307_02F0D7_CDF4, S1A_IW_SLC__1SDV_20190228T161207_20190228T161234_026132_02EA79_658C, S1A_IW_SLC__1SDV_20190216T161207_20190216T161234_025957_02E43D_1A36, S1A_IW_SLC__1SDV_20190204T161207_20190204T161234_025782_02DE0A_AFD0, S1A_IW_SLC__1SDV_20190123T161207_20190123T161234_025607_02D7AF_B3EF, S1A_IW_SLC__1SDV_20190111T161208_20190111T161234_025432_02D14C_1CE2, S1A_IW_SLC__1SDV_20181230T161208_20181230T161235_025257_02CB01_DDC2, S1A_IW_SLC__1SDV_20181218T161208_20181218T161235_025082_02C4AB_CB92, S1A_IW_SLC__1SDV_20181206T161209_20181206T161236_024907_02BE52_7F8B, S1A_IW_SLC__1SDV_20181112T161210_20181112T161237_024557_02B205_EE96, S1A_IW_SLC__1SDV_20181031T161210_20181031T161237_024382_02ABA5_1060, S1A_IW_SLC__1SDV_20181019T161210_20181019T161237_024207_02A5F4_0D73, S1A_IW_SLC__1SDV_20181007T161210_20181007T161237_024032_02A043_0977, S1A_IW_SLC__1SDV_20180925T161209_20180925T161236_023857_029A88_2E0D, S1A_IW_SLC__1SDV_20180901T161209_20180901T161236_023507_028F3D_C847, S1A_IW_SLC__1SDV_20180820T161208_20180820T161235_023332_0289AD_5EFE, S1A_IW_SLC__1SDV_20180808T161207_20180808T161234_023157_028404_0500, S1A_IW_SLC__1SDV_20180727T161207_20180727T161234_022982_027E8C_B964, S1A_IW_SLC__1SDV_20180715T161206_20180715T161233_022807_027905_12D0, S1A_IW_SLC__1SDV_20180703T161205_20180703T161232_022632_0273BB_60ED, S1A_IW_SLC__1SDV_20180621T161205_20180621T161232_022457_026EA1_7B49, S1A_IW_SLC__1SDV_20180609T161204_20180609T161231_022282_02694F_6F90, S1A_IW_SLC__1SDV_20180516T161202_20180516T161229_021932_025E3A_80D9, S1A_IW_SLC__1SDV_20180504T161202_20180504T161229_021757_0258AB_5257, S1A_IW_SLC__1SDV_20180422T161201_20180422T161228_021582_025323_C3D4, S1A_IW_SLC__1SDV_20180410T161201_20180410T161228_021407_024DAD_6105, S1A_IW_SLC__1SDV_20180329T161200_20180329T161227_021232_024838_DA10, S1A_IW_SLC__1SDV_20180317T161200_20180317T161227_021057_0242AE_DC81, S1A_IW_SLC__1SDV_20180305T161200_20180305T161227_020882_023D1D_32B9, S1A_IW_SLC__1SDV_20180221T161200_20180221T161227_020707_023798_07E5, S1A_IW_SLC__1SDV_20180209T161200_20180209T161227_020532_023203_583B, S1A_IW_SLC__1SDV_20180128T161200_20180128T161227_020357_022C68_9638, S1A_IW_SLC__1SDV_20180116T161201_20180116T161228_020182_0226E1_9121, S1A_IW_SLC__1SDV_20180104T161201_20180104T161228_020007_022150_C33D, S1A_IW_SLC__1SDV_20171223T161202_20171223T161229_019832_021BCB_ECE6, S1A_IW_SLC__1SDV_20171211T161202_20171211T161229_019657_021668_D20C, S1A_IW_SLC__1SDV_20171129T161203_20171129T161230_019482_0210EE_54AB, S1A_IW_SLC__1SDV_20171117T161203_20171117T161230_019307_020B69_5ECA, S1A_IW_SLC__1SDV_20171105T161203_20171105T161230_019132_0205F6_C16B, S1A_IW_SLC__1SDV_20171024T161203_20171024T161230_018957_020098_803B, S1A_IW_SLC__1SDV_20171012T161203_20171012T161230_018782_01FB3C_849C, S1A_IW_SLC__1SDV_20170930T161203_20170930T161230_018607_01F5ED_996D, S1A_IW_SLC__1SDV_20170918T161203_20170918T161230_018432_01F08E_9167, S1A_IW_SLC__1SDV_20170906T161202_20170906T161229_018257_01EB22_E956, S1A_IW_SLC__1SDV_20170825T161202_20170825T161229_018082_01E5CF_5747, S1A_IW_SLC__1SDV_20170813T161201_20170813T161228_017907_01E07F_7F41, S1A_IW_SLC__1SDV_20170801T161201_20170801T161228_017732_01DB35_AF59, S1A_IW_SLC__1SDV_20170720T161200_20170720T161227_017557_01D5D6_F00C, S1A_IW_SLC__1SDV_20170708T161159_20170708T161226_017382_01D081_3FBE, S1A_IW_SLC__1SDV_20170626T161159_20170626T161226_017207_01CB3F_6D52, S1A_IW_SLC__1SDV_20170614T161158_20170614T161225_017032_01C5EA_C37C, S1A_IW_SLC__1SSV_20170602T161157_20170602T161224_016857_01C07F_6500, S1A_IW_SLC__1SSV_20170521T161156_20170521T161223_016682_01BB19_FE9E, S1B_IW_SLC__1SSV_20170316T161112_20170316T161139_004736_008452_EE3F, S1B_IW_SLC__1SSV_20170304T161111_20170304T161138_004561_007F26_35CA, S1B_IW_SLC__1SSV_20170220T161112_20170220T161139_004386_007A0B_F86F, S1B_IW_SLC__1SSV_20170127T161112_20170127T161139_004036_006F95_AB4B, S1B_IW_SLC__1SSV_20170103T161113_20170103T161139_003686_00653D_0231, S1B_IW_SLC__1SSV_20161210T161115_20161210T161141_003336_005B1F_37B5, S1B_IW_SLC__1SSV_20161116T161115_20161116T161142_002986_00512D_AAFE, S1B_IW_SLC__1SSV_20161023T161115_20161023T161142_002636_004745_1F63, S1A_IW_SLC__1SSV_20150719T161147_20150719T161214_006882_0094A9_694E, S1A_IW_SLC__1SSV_20150625T161146_20150625T161213_006532_008AEA_0F7C, S1A_IW_SLC__1SSV_20150601T161145_20150601T161213_006182_0080D3_7FF6, S1A_IW_SLC__1SSV_20150508T161143_20150508T161211_005832_007814_9F2E, S1A_IW_SLC__1SSV_20150414T161142_20150414T161210_005482_006FEF_5D96, S1A_IW_SLC__1SSV_20150321T161141_20150321T161209_005132_00676D_D082, S1A_IW_SLC__1SSV_20150225T161140_20150225T161208_004782_005F00_A2C0, S1A_IW_SLC__1SSV_20150108T161142_20150108T161209_004082_004EFA_53E2, S1A_IW_SLC__1SSV_20141215T161143_20141215T161211_003732_004718_D707, S1A_IW_SLC__1SSV_20141121T161143_20141121T161211_003382_003EF1_9B9E, S1A_IW_SLC__1SSV_20141028T161144_20141028T161212_003032_003762_F7E1

### Share Results

- [ ] Google Earth Engine (GEE)
- [ ] NASA Distributed Active Archive Centers (DAAC) User Acceptance Testing (UAT)

### Additional Notes

Scene for static processing:
S1A_IW_SLC__1SDV_20230713T161236_20230713T161303_049407_05F0ED_B461

**Comment by niarenaw** [comment]
outputs: [issue19_rtc.txt](https://github.com/nasa/opera-sds/files/12877053/issue19_rtc.txt)
