### ISSUE TITLE
[Processing Request]: Mato Grosso, Descending, High Priority

### ISSUE THREAD

**Issue by Alex-Lewandowski** [nasa/opera-sds#20]
### Venue

PST

### Product

RTC-S1

### SAS Version

latest

### SDS Version

latest

### Input Data

S1A_IW_SLC__1SDV_20220508T090052_20220508T090120_043117_052635_69D2, S1A_IW_SLC__1SDV_20220426T090052_20220426T090120_042942_05205F_F0D0, S1A_IW_SLC__1SDV_20220414T090051_20220414T090119_042767_051A9D_6129, S1A_IW_SLC__1SDV_20220402T090051_20220402T090119_042592_0514B8_EF0D, S1A_IW_SLC__1SDV_20220321T090051_20220321T090119_042417_050ECC_FC5F, S1A_IW_SLC__1SDV_20220309T090050_20220309T090118_042242_0508E3_D789, S1A_IW_SLC__1SDV_20220225T090051_20220225T090119_042067_0502E9_ABD3, S1A_IW_SLC__1SDV_20220213T090051_20220213T090119_041892_04FCDC_5F37, S1A_IW_SLC__1SDV_20220201T090051_20220201T090119_041717_04F6C3_1598, S1A_IW_SLC__1SDV_20220120T090051_20220120T090119_041542_04F0C5_6690, S1A_IW_SLC__1SDV_20220108T090052_20220108T090120_041367_04EB14_07ED, S1A_IW_SLC__1SDV_20211227T090052_20211227T090120_041192_04E517_140B, S1A_IW_SLC__1SDV_20211215T090053_20211215T090121_041017_04DF59_DD57, S1A_IW_SLC__1SDV_20211203T090054_20211203T090121_040842_04D959_7900, S1A_IW_SLC__1SDV_20211121T090054_20211121T090122_040667_04D33F_D4A5, S1A_IW_SLC__1SDV_20211109T090054_20211109T090122_040492_04CD3D_68C1, S1A_IW_SLC__1SDV_20211028T090055_20211028T090122_040317_04C718_B6D4, S1A_IW_SLC__1SDV_20211016T090055_20211016T090123_040142_04C104_C824, S1A_IW_SLC__1SDV_20211004T090055_20211004T090122_039967_04BAF8_DD9C, S1A_IW_SLC__1SDV_20210922T090054_20210922T090122_039792_04B4E0_F778, S1A_IW_SLC__1SDV_20210910T090054_20210910T090122_039617_04AEF6_EC7E, S1A_IW_SLC__1SDV_20210829T090053_20210829T090121_039442_04A8E3_62CB, S1A_IW_SLC__1SDV_20210817T090053_20210817T090121_039267_04A2F0_7960, S1A_IW_SLC__1SDV_20210805T090052_20210805T090120_039092_049CE0_2BAD, S1A_IW_SLC__1SDV_20210724T090051_20210724T090119_038917_049793_5A17, S1A_IW_SLC__1SDV_20210712T090051_20210712T090119_038742_049258_8F73, S1A_IW_SLC__1SDV_20210630T090050_20210630T090118_038567_048D0F_13AA, S1A_IW_SLC__1SDV_20210618T090049_20210618T090117_038392_0487D2_447D, S1A_IW_SLC__1SDV_20210606T090048_20210606T090116_038217_04829F_00F0, S1A_IW_SLC__1SDV_20160831T090023_20160831T090051_012842_014445_B59E, S1A_IW_SLC__1SDV_20160819T090023_20160819T090051_012667_013E55_BF7E, S1A_IW_SLC__1SDV_20160807T090022_20160807T090050_012492_013895_CC66, S1A_IW_SLC__1SDV_20160726T090022_20160726T090050_012317_0132B3_A1C2, S1A_IW_SLC__1SDV_20160714T090021_20160714T090049_012142_012D09_B3F4, S1A_IW_SLC__1SDV_20160608T090019_20160608T090047_011617_011C30_75B1, S1A_IW_SLC__1SDV_20160527T090018_20160527T090046_011442_0116B9_1B41, S1A_IW_SLC__1SDV_20160515T090018_20160515T090046_011267_0110F5_35C3, S1A_IW_SLC__1SDV_20160503T090014_20160503T090042_011092_010B65_049B, S1A_IW_SLC__1SDV_20160421T090014_20160421T090041_010917_0105DC_3B59, S1A_IW_SLC__1SDV_20160409T090013_20160409T090041_010742_01008D_735B, S1A_IW_SLC__1SDV_20160316T090012_20160316T090040_010392_00F662_7622, S1A_IW_SLC__1SDV_20160221T090012_20160221T090042_010042_00EC80_7B02, S1A_IW_SLC__1SDV_20160116T090013_20160116T090041_009517_00DD1C_0C81, S1A_IW_SLC__1SDV_20160104T090013_20160104T090041_009342_00D81E_9B15, S1A_IW_SLC__1SDV_20151223T090014_20151223T090041_009167_00D320_87CA, S1A_IW_SLC__1SDV_20151129T090014_20151129T090042_008817_00C94F_E4C6, S1A_IW_SLC__1SDV_20151117T090015_20151117T090045_008642_00C47A_C950

### Share Results

- [ ] Google Earth Engine (GEE)
- [ ] NASA Distributed Active Archive Centers (DAAC) User Acceptance Testing (UAT)

### Additional Notes

Scenes for static file processing:
S1A_IW_SLC__1SDV_20220508T090052_20220508T090120_043117_052635_69D2, S1A_IW_SLC__1SDV_20151117T090015_20151117T090045_008642_00C47A_C950, S1A_IW_SLC__1SDV_20151223T090014_20151223T090041_009167_00D320_87CA, S1A_IW_SLC__1SDV_20160421T090014_20160421T090041_010917_0105DC_3B59, S1A_IW_SLC__1SDV_20220120T090051_20220120T090119_041542_04F0C5_6690, S1A_IW_SLC__1SDV_20160515T090018_20160515T090046_011267_0110F5_35C3, S1A_IW_SLC__1SDV_20210606T090048_20210606T090116_038217_04829F_00F0

**Comment by niarenaw** [comment]
outputs: [issue20_rtc.txt](https://github.com/nasa/opera-sds/files/12877056/issue20_rtc.txt)
