### ISSUE TITLE
[Processing Request]: VT/NH, Ascending, High Priority

### ISSUE THREAD

**Issue by Alex-Lewandowski** [nasa/opera-sds#21]
### Venue

PST

### Product

RTC-S1

### SAS Version

latest

### SDS Version

latest

### Input Data

S1A_IW_SLC__1SDV_20210122T224355_20210122T224422_036257_0440CC_9618, S1A_IW_SLC__1SDV_20210215T224354_20210215T224421_036607_044CF8_7921, S1A_IW_SLC__1SDV_20210311T224354_20210311T224421_036957_04591F_12E2, S1A_IW_SLC__1SDV_20210404T224355_20210404T224422_037307_04653E_86CC, S1A_IW_SLC__1SDV_20210428T224355_20210428T224429_037657_04715F_F6E9, S1A_IW_SLC__1SDV_20210627T224359_20210627T224426_038532_048C0E_3C27, S1A_IW_SLC__1SDV_20210721T224400_20210721T224427_038882_04968E_3A92, S1A_IW_SLC__1SDV_20210814T224402_20210814T224429_039232_04A1BA_E9EF, S1A_IW_SLC__1SDV_20210907T224403_20210907T224430_039582_04ADC8_9FD3, S1A_IW_SLC__1SDV_20211013T224404_20211013T224431_040107_04BFCE_7508, S1A_IW_SLC__1SDV_20211106T224404_20211106T224431_040457_04CC01_0E7A, S1A_IW_SLC__1SDV_20211130T224403_20211130T224430_040807_04D820_996A, S1A_IW_SLC__1SDV_20211212T224402_20211212T224429_040982_04DE2D_1F0D

### Share Results

- [ ] Google Earth Engine (GEE)
- [ ] NASA Distributed Active Archive Centers (DAAC) User Acceptance Testing (UAT)

### Additional Notes

Scenes for static file processing:
S1A_IW_SLC__1SDV_20211212T224402_20211212T224429_040982_04DE2D_1F0D, S1A_IW_SLC__1SDV_20210428T224355_20210428T224429_037657_04715F_F6E9

**Comment by niarenaw** [comment]
outputs: [issue21_rtc.txt](https://github.com/nasa/opera-sds/files/12877058/issue21_rtc.txt)
