### ISSUE TITLE
[Processing Request]: VT/NH, Descending, High Priority

### ISSUE THREAD

**Issue by Alex-Lewandowski** [nasa/opera-sds#22]
### Venue

PST

### Product

RTC-S1

### SAS Version

latest

### SDS Version

latest

### Input Data

S1A_IW_SLC__1SDV_20200830T105658_20200830T105726_034135_03F6EB_BB87, S1A_IW_SLC__1SDV_20220329T105704_20220329T105732_042535_0512CE_10EF, S1A_IW_SLC__1SDV_20220410T105704_20220410T105732_042710_0518B7_3CA4, S1A_IW_SLC__1SDV_20220504T105705_20220504T105733_043060_052456_11B8, S1A_IW_SLC__1SDV_20220609T105708_20220609T105736_043585_053430_5A3C, S1A_IW_SLC__1SDV_20220703T105709_20220703T105737_043935_053EA1_E280, S1A_IW_SLC__1SDV_20220727T105711_20220727T105739_044285_054917_0ACC, S1A_IW_SLC__1SDV_20220820T105712_20220820T105740_044635_05540A_7207, S1A_IW_SLC__1SDV_20220913T105714_20220913T105741_044985_055FD0_0DCC, S1A_IW_SLC__1SDV_20221007T105714_20221007T105742_045335_056B92_DDCA, S1A_IW_SLC__1SDV_20221031T105714_20221031T105742_045685_0576AF_4744, S1A_IW_SLC__1SDV_20221124T105711_20221124T105739_046035_05827B_67C5, S1A_IW_SLC__1SDV_20221218T105709_20221218T105737_046385_058E74_8420

### Share Results

- [ ] Google Earth Engine (GEE)
- [ ] NASA Distributed Active Archive Centers (DAAC) User Acceptance Testing (UAT)

### Additional Notes

Scenes for static file processing:
S1A_IW_SLC__1SDV_20221218T105709_20221218T105737_046385_058E74_8420, S1A_IW_SLC__1SDV_20220329T105704_20220329T105732_042535_0512CE_10EF

**Comment by niarenaw** [comment]
outputs: [issue22_rtc.txt](https://github.com/nasa/opera-sds/files/12877060/issue22_rtc.txt)
