### ISSUE TITLE
[Processing Request]: CA Rosamond, Ascending, Medium Priority

### ISSUE THREAD

**Issue by Alex-Lewandowski** [nasa/opera-sds#25]
### Venue

PST

### Product

RTC-S1

### SAS Version

latest

### SDS Version

latest

### Input Data

S1A_IW_SLC__1SDV_20230707T015044_20230707T015112_049311_05EDF6_1A68, S1A_IW_SLC__1SDV_20230625T015043_20230625T015111_049136_05E895_CBD9, S1A_IW_SLC__1SDV_20230613T015042_20230613T015110_048961_05E341_A548, S1A_IW_SLC__1SDV_20230601T015042_20230601T015110_048786_05DDF3_24DF, S1A_IW_SLC__1SDV_20230520T015041_20230520T015109_048611_05D8B8_7DF1, S1A_IW_SLC__1SDV_20230508T015041_20230508T015109_048436_05D381_718B, S1A_IW_SLC__1SDV_20230426T015040_20230426T015108_048261_05CDA6_674E, S1A_IW_SLC__1SDV_20230414T015040_20230414T015108_048086_05C7C6_C6BB, S1A_IW_SLC__1SDV_20230402T015039_20230402T015107_047911_05C1D6_3F30, S1A_IW_SLC__1SDV_20230321T015039_20230321T015107_047736_05BBFD_70D3, S1A_IW_SLC__1SDV_20230309T015038_20230309T015106_047561_05B60F_D3B2, S1A_IW_SLC__1SDV_20230225T015039_20230225T015107_047386_05B025_CFAD, S1A_IW_SLC__1SDV_20230213T015039_20230213T015107_047211_05AA2E_9973, S1A_IW_SLC__1SDV_20230201T015039_20230201T015107_047036_05A453_EBD8, S1A_IW_SLC__1SDV_20230120T015039_20230120T015107_046861_059E73_418D, S1A_IW_SLC__1SDV_20230108T015040_20230108T015108_046686_05988B_CAAE, S1A_IW_SLC__1SDV_20221227T015041_20221227T015109_046511_0592AC_6E76, S1A_IW_SLC__1SDV_20221215T015041_20221215T015109_046336_058CB1_D06E, S1A_IW_SLC__1SDV_20221203T015042_20221203T015110_046161_0586BC_F9C8, S1A_IW_SLC__1SDV_20221121T015043_20221121T015111_045986_0580C5_2A46, S1A_IW_SLC__1SDV_20221109T015043_20221109T015110_045811_057AE4_078A, S1A_IW_SLC__1SDV_20221028T015043_20221028T015111_045636_0574F3_2909, S1A_IW_SLC__1SDV_20221016T015043_20221016T015111_045461_056FC0_6681, S1A_IW_SLC__1SDV_20221004T015043_20221004T015111_045286_0569EA_E640, S1A_IW_SLC__1SDV_20220922T015042_20220922T015110_045111_05640A_2DD1, S1A_IW_SLC__1SDV_20220910T015043_20220910T015111_044936_055E1F_60F6, S1A_IW_SLC__1SDV_20220829T015042_20220829T015110_044761_055844_BA2A, S1A_IW_SLC__1SDV_20220817T015042_20220817T015109_044586_055259_E511, S1A_IW_SLC__1SDV_20220805T015041_20220805T015109_044411_054CC1_739B, S1A_IW_SLC__1SDV_20220724T015040_20220724T015108_044236_05479C_17B8, S1A_IW_SLC__1SDV_20220712T015039_20220712T015107_044061_054262_0891, S1A_IW_SLC__1SDV_20220630T015039_20220630T015106_043886_053D2F_F49E, S1A_IW_SLC__1SDV_20220618T015038_20220618T015106_043711_0537EE_D244, S1A_IW_SLC__1SDV_20220606T015037_20220606T015105_043536_0532BA_5046, S1A_IW_SLC__1SDV_20220525T015036_20220525T015104_043361_052D8D_DCAE, S1A_IW_SLC__1SDV_20220513T015035_20220513T015103_043186_052856_E534, S1A_IW_SLC__1SDV_20220501T015035_20220501T015102_043011_0522A4_42CC, S1A_IW_SLC__1SDV_20220419T015034_20220419T015102_042836_051CE2_39A8, S1A_IW_SLC__1SDV_20220407T015033_20220407T015101_042661_051705_FD8D, S1A_IW_SLC__1SDV_20220326T015033_20220326T015101_042486_051118_6B3C, S1A_IW_SLC__1SDV_20220314T015033_20220314T015101_042311_050B23_CCD5, S1A_IW_SLC__1SDV_20220218T015033_20220218T015101_041961_04FF34_E691, S1A_IW_SLC__1SDV_20220206T015033_20220206T015101_041786_04F91C_DC3C, S1A_IW_SLC__1SDV_20220125T015034_20220125T015102_041611_04F317_A805, S1A_IW_SLC__1SDV_20220113T015034_20220113T015102_041436_04ED43_9F80, S1A_IW_SLC__1SDV_20220101T015035_20220101T015103_041261_04E75E_3C18, S1A_IW_SLC__1SDV_20211220T015035_20211220T015103_041086_04E18D_A045, S1A_IW_SLC__1SDV_20211208T015036_20211208T015104_040911_04DBAC_2D29, S1A_IW_SLC__1SDV_20211126T015036_20211126T015104_040736_04D592_ED2C, S1A_IW_SLC__1SDV_20211114T015037_20211114T015105_040561_04CF8E_FCD7, S1A_IW_SLC__1SDV_20211102T015040_20211102T015108_040386_04C96F_CE80, S1A_IW_SLC__1SDV_20211021T015040_20211021T015108_040211_04C35D_EC2C, S1A_IW_SLC__1SDV_20211009T015040_20211009T015108_040036_04BD45_C5B8, S1A_IW_SLC__1SDV_20210927T015040_20210927T015108_039861_04B734_A229, S1A_IW_SLC__1SDV_20210915T015039_20210915T015107_039686_04B155_C63B, S1A_IW_SLC__1SDV_20210903T015039_20210903T015107_039511_04AB3F_C333, S1A_IW_SLC__1SDV_20210822T015038_20210822T015106_039336_04A543_28B2, S1A_IW_SLC__1SDV_20210810T015038_20210810T015105_039161_049F3C_B9BF, S1A_IW_SLC__1SDV_20210729T015037_20210729T015105_038986_04998B_34D4, S1A_IW_SLC__1SDV_20210717T015036_20210717T015104_038811_049456_3E46, S1A_IW_SLC__1SDV_20210705T015035_20210705T015103_038636_048F19_3780, S1A_IW_SLC__1SDV_20210623T015035_20210623T015103_038461_0489D0_98E2, S1A_IW_SLC__1SDV_20210611T015034_20210611T015102_038286_048499_8004, S1A_IW_SLC__1SDV_20210530T015033_20210530T015101_038111_047F6C_EE00, S1A_IW_SLC__1SDV_20210518T015032_20210518T015100_037936_047A28_1DCB, S1A_IW_SLC__1SDV_20210506T015032_20210506T015100_037761_0474E2_5BB9, S1A_IW_SLC__1SDV_20210424T015031_20210424T015059_037586_046ED2_DA36, S1A_IW_SLC__1SDV_20210412T015031_20210412T015059_037411_0468C7_6259, S1A_IW_SLC__1SDV_20210331T015030_20210331T015058_037236_0462BD_4F81, S1A_IW_SLC__1SDV_20210319T015030_20210319T015058_037061_045CB1_063A, S1A_IW_SLC__1SDV_20210307T015030_20210307T015058_036886_045698_5779, S1A_IW_SLC__1SDV_20210223T015030_20210223T015058_036711_04507F_CF4B, S1A_IW_SLC__1SDV_20210211T015030_20210211T015058_036536_044A61_2578, S1A_IW_SLC__1SDV_20210130T015031_20210130T015059_036361_044451_A5BC, S1A_IW_SLC__1SDV_20210106T015032_20210106T015059_036011_04381A_394A, S1A_IW_SLC__1SDV_20201225T015032_20201225T015100_035836_043200_05C4, S1A_IW_SLC__1SDV_20201213T015033_20201213T015101_035661_042BFB_4AE6, S1A_IW_SLC__1SDV_20201201T015033_20201201T015101_035486_0425FA_7B42, S1A_IW_SLC__1SDV_20201119T015034_20201119T015102_035311_041FEE_C819, S1A_IW_SLC__1SDV_20201107T015034_20201107T015102_035136_0419CE_F4EF, S1A_IW_SLC__1SDV_20201026T015034_20201026T015102_034961_0413CB_B982, S1A_IW_SLC__1SDV_20201014T015034_20201014T015102_034786_040DBF_8DEC, S1A_IW_SLC__1SDV_20201002T015034_20201002T015102_034611_0407A2_488F, S1A_IW_SLC__1SDV_20200920T015034_20200920T015102_034436_040182_8446, S1A_IW_SLC__1SDV_20200908T015033_20200908T015101_034261_03FB47_238D, S1A_IW_SLC__1SDV_20200827T015033_20200827T015101_034086_03F51E_AE5F, S1A_IW_SLC__1SDV_20200815T015032_20200815T015100_033911_03EEF2_FD43, S1A_IW_SLC__1SDV_20200803T015031_20200803T015059_033736_03E8F9_DD8B, S1A_IW_SLC__1SDV_20200722T015031_20200722T015059_033561_03E39D_5DB4, S1A_IW_SLC__1SDV_20200710T015030_20200710T015058_033386_03DE40_5E7A, S1A_IW_SLC__1SDV_20200628T015029_20200628T015057_033211_03D8F2_76C2, S1A_IW_SLC__1SDV_20200616T015029_20200616T015056_033036_03D3A1_BCBE, S1A_IW_SLC__1SDV_20200604T015028_20200604T015056_032861_03CE63_0CAC, S1A_IW_SLC__1SDV_20200523T015027_20200523T015055_032686_03C92E_AC89, S1A_IW_SLC__1SDV_20200511T015026_20200511T015054_032511_03C3E0_300E, S1A_IW_SLC__1SDV_20200429T015026_20200429T015054_032336_03BE0C_874D, S1A_IW_SLC__1SDV_20200417T015025_20200417T015053_032161_03B7E9_FCE2, S1A_IW_SLC__1SDV_20200324T015024_20200324T015052_031811_03AB9C_D24B, S1A_IW_SLC__1SDV_20200312T015024_20200312T015052_031636_03A571_0A52, S1A_IW_SLC__1SDV_20200229T015024_20200229T015052_031461_039F54_4131, S1A_IW_SLC__1SDV_20200217T015024_20200217T015052_031286_039955_4CA1, S1A_IW_SLC__1SDV_20200205T015025_20200205T015053_031111_039347_1BBE, S1A_IW_SLC__1SDV_20191231T015026_20191231T015054_030586_0380F1_8567, S1A_IW_SLC__1SDV_20191207T015027_20191207T015055_030236_0374DB_AA56, S1A_IW_SLC__1SDV_20191125T015027_20191125T015055_030061_036ED3_8C00, S1A_IW_SLC__1SDV_20191113T015028_20191113T015056_029886_0368C3_E5CC, S1A_IW_SLC__1SDV_20191101T015028_20191101T015056_029711_03629F_2A2C, S1A_IW_SLC__1SDV_20191020T015028_20191020T015055_029536_035C8B_5A7F, S1A_IW_SLC__1SDV_20191008T015028_20191008T015056_029361_03567D_3F6F, S1A_IW_SLC__1SDV_20190926T015028_20190926T015055_029186_035074_5C26, S1A_IW_SLC__1SDV_20190902T015026_20190902T015054_028836_03446D_7CDD, S1A_IW_SLC__1SDV_20190809T015025_20190809T015053_028486_03383E_78BE, S1A_IW_SLC__1SDV_20190728T015024_20190728T015052_028311_0332DD_2779, S1A_IW_SLC__1SDV_20190716T015024_20190716T015052_028136_032D86_A334, S1A_IW_SLC__1SDV_20190704T015023_20190704T015051_027961_03283A_D6EA, S1A_IW_SLC__1SDV_20190622T015022_20190622T015050_027786_0322F1_137C, S1A_IW_SLC__1SDV_20190610T015021_20190610T015049_027611_031DB6_215F, S1A_IW_SLC__1SDV_20190529T015021_20190529T015049_027436_031855_748B, S1A_IW_SLC__1SDV_20190517T015020_20190517T015048_027261_0312DF_AEC6, S1A_IW_SLC__1SDV_20190423T015019_20190423T015047_026911_0306E9_7D2B, S1A_IW_SLC__1SDV_20190411T015019_20190411T015046_026736_030095_9D69, S1A_IW_SLC__1SDV_20190330T015018_20190330T015046_026561_02FA29_1322, S1A_IW_SLC__1SDV_20190318T015018_20190318T015046_026386_02F3BB_0749, S1A_IW_SLC__1SDV_20190306T015018_20190306T015046_026211_02ED47_8886, S1A_IW_SLC__1SDV_20190222T015018_20190222T015046_026036_02E706_16A0, S1A_IW_SLC__1SDV_20190210T015018_20190210T015046_025861_02E0D3_15AA, S1A_IW_SLC__1SDV_20190117T015019_20190117T015047_025511_02D422_3386, S1A_IW_SLC__1SDV_20170208T015003_20170208T015030_015186_018DBD_A143, S1B_IW_SLC__1SDV_20170202T014921_20170202T014948_004115_0071E4_8681, S1A_IW_SLC__1SDV_20170127T015004_20170127T015030_015011_018852_7E90, S1A_IW_SLC__1SSV_20170115T015004_20170115T015031_014836_0182EE_83F0, S1B_IW_SLC__1SDV_20170109T014922_20170109T014949_003765_00678C_BA11, S1A_IW_SLC__1SDV_20170103T015004_20170103T015030_014661_017D92_6421, S1A_IW_SLC__1SSV_20161222T015006_20161222T015033_014486_017831_6433, S1B_IW_SLC__1SDV_20161216T014924_20161216T014951_003415_005D56_0797, S1A_IW_SLC__1SDV_20161210T015006_20161210T015032_014311_0172BA_DDD9, S1A_IW_SLC__1SSV_20161128T015007_20161128T015034_014136_016D2E_9AFD, S1A_IW_SLC__1SDV_20161116T015007_20161116T015033_013961_0167D4_4555, S1A_IW_SLC__1SSV_20161104T015007_20161104T015034_013786_01625F_0065, S1A_IW_SLC__1SDV_20161023T015007_20161023T015033_013611_015CEC_D576, S1A_IW_SLC__1SSV_20161011T015007_20161011T015034_013436_01576D_C237, S1A_IW_SLC__1SDV_20160905T015006_20160905T015032_012911_01468C_22D9, S1A_IW_SLC__1SDV_20160824T015005_20160824T015024_012736_0140B0_58FD, S1A_IW_SLC__1SDV_20160812T015005_20160812T015026_012561_013ADB_C3A9, S1A_IW_SLC__1SSV_20160731T015005_20160731T015032_012386_013504_6F36, S1A_IW_SLC__1SDV_20160719T015004_20160719T015030_012211_012F4C_145B, S1A_IW_SLC__1SSV_20160707T015003_20160707T015030_012036_012994_AE8B, S1A_IW_SLC__1SSV_20160613T015002_20160613T015029_011686_011E6A_044B, S1A_IW_SLC__1SDV_20160601T015001_20160601T015027_011511_0118F2_7976, S1A_IW_SLC__1SSV_20160520T015000_20160520T015027_011336_01133B_E88C, S1A_IW_SLC__1SDV_20160508T015000_20160508T015026_011161_010D92_199B, S1A_IW_SLC__1SSV_20160426T014959_20160426T015026_010986_010809_35DD, S1A_IW_SLC__1SDV_20160414T014959_20160414T015025_010811_0102AA_8E34, S1A_IW_SLC__1SSV_20160402T014958_20160402T015025_010636_00FD66_56C9, S1A_IW_SLC__1SDV_20160321T014958_20160321T015024_010461_00F862_34FD, S1A_IW_SLC__1SSV_20160214T014957_20160214T015024_009936_00E95D_0753, S1A_IW_SLC__1SDV_20160109T014958_20160109T015024_009411_00DA1D_E610, S1A_IW_SLC__1SDV_20151216T014959_20151216T015025_009061_00D021_188E, S1A_IW_SLC__1SDV_20151122T014959_20151122T015026_008711_00C662_1E71, S1A_IW_SLC__1SSV_20150502T014955_20150502T015023_005736_0075D4_6CED, S1A_IW_SLC__1SDV_20150327T014954_20150327T015021_005211_00694B_4E66, S1A_IW_SLC__1SSV_20150207T014953_20150207T015023_004511_005899_9C44

### Share Results

- [ ] Google Earth Engine (GEE)
- [ ] NASA Distributed Active Archive Centers (DAAC) User Acceptance Testing (UAT)

### Additional Notes

Scenes for static file processing:
S1A_IW_SLC__1SSV_20150207T014953_20150207T015023_004511_005899_9C44, S1A_IW_SLC__1SDV_20160824T015005_20160824T015024_012736_0140B0_58FD

**Comment by niarenaw** [comment]
Completed in [[Processing Request]: R2 Final CalVal processing#13](https://github.com/nasa/opera-sds/issues/13)
