### ISSUE TITLE
[Processing Request]: CA Rosamond, Descending, Medium Priority

### ISSUE THREAD

**Issue by Alex-Lewandowski** [nasa/opera-sds#26]
### Venue

PST

### Product

RTC-S1

### SAS Version

latest

### SDS Version

latest

### Input Data

S1A_IW_SLC__1SDV_20230707T135227_20230707T135255_049318_05EE35_0F4B, S1A_IW_SLC__1SDV_20230625T135227_20230625T135254_049143_05E8D2_E4F6, S1A_IW_SLC__1SDV_20230613T135226_20230613T135254_048968_05E383_1D61, S1A_IW_SLC__1SDV_20230601T135225_20230601T135253_048793_05DE2A_822B, S1A_IW_SLC__1SDV_20230520T135225_20230520T135253_048618_05D8F4_B44F, S1A_IW_SLC__1SDV_20230508T135224_20230508T135252_048443_05D3C7_C37F, S1A_IW_SLC__1SDV_20230426T135223_20230426T135251_048268_05CDED_7F8A, S1A_IW_SLC__1SDV_20230414T135223_20230414T135251_048093_05C80D_84E9, S1A_IW_SLC__1SDV_20230402T135223_20230402T135250_047918_05C21E_13E5, S1A_IW_SLC__1SDV_20230321T135222_20230321T135250_047743_05BC46_9FC5, S1A_IW_SLC__1SDV_20230309T135222_20230309T135249_047568_05B656_0B22, S1A_IW_SLC__1SDV_20230225T135222_20230225T135250_047393_05B06D_E7A0, S1A_IW_SLC__1SDV_20230213T135222_20230213T135249_047218_05AA76_DC83, S1A_IW_SLC__1SDV_20230201T135223_20230201T135250_047043_05A49A_B6F7, S1A_IW_SLC__1SDV_20230120T135223_20230120T135250_046868_059EBC_E46E, S1A_IW_SLC__1SDV_20230108T135223_20230108T135251_046693_0598D3_A89F, S1A_IW_SLC__1SDV_20221227T135224_20221227T135252_046518_0592F4_0CF9, S1A_IW_SLC__1SDV_20221215T135224_20221215T135252_046343_058CF7_B84A, S1A_IW_SLC__1SDV_20221203T135225_20221203T135253_046168_058705_9F91, S1A_IW_SLC__1SDV_20221121T135226_20221121T135254_045993_058110_FC08, S1A_IW_SLC__1SDV_20221109T135226_20221109T135254_045818_057B2E_C068, S1A_IW_SLC__1SDV_20221028T135226_20221028T135254_045643_05753C_231F, S1A_IW_SLC__1SDV_20221016T135226_20221016T135254_045468_056FF4_407E, S1A_IW_SLC__1SDV_20221004T135226_20221004T135254_045293_056A34_1026, S1A_IW_SLC__1SDV_20220922T135225_20220922T135253_045118_05644B_B8CA, S1A_IW_SLC__1SDV_20220910T135226_20220910T135254_044943_055E64_3609, S1A_IW_SLC__1SDV_20220829T135225_20220829T135253_044768_05588D_6C6B, S1A_IW_SLC__1SDV_20220817T135225_20220817T135253_044593_0552A2_ECF9, S1A_IW_SLC__1SDV_20220805T135224_20220805T135252_044418_054CF6_7B86, S1A_IW_SLC__1SDV_20220724T135223_20220724T135251_044243_0547D4_996C, S1A_IW_SLC__1SDV_20220712T135222_20220712T135250_044068_05429F_69C7, S1A_IW_SLC__1SDV_20220630T135222_20220630T135250_043893_053D68_FD13, S1A_IW_SLC__1SDV_20220618T135221_20220618T135248_043718_05382C_B558, S1A_IW_SLC__1SDV_20220606T135220_20220606T135248_043543_0532F8_90E6, S1A_IW_SLC__1SDV_20220525T135219_20220525T135247_043368_052DC9_C810, S1A_IW_SLC__1SDV_20220513T135219_20220513T135246_043193_052894_A1C7, S1A_IW_SLC__1SDV_20220501T135218_20220501T135246_043018_0522EA_72F9, S1A_IW_SLC__1SDV_20220419T135217_20220419T135245_042843_051D21_DD4E, S1A_IW_SLC__1SDV_20220407T135217_20220407T135245_042668_051743_3469, S1A_IW_SLC__1SDV_20220326T135217_20220326T135245_042493_05115D_6EE3, S1A_IW_SLC__1SDV_20220314T135216_20220314T135244_042318_050B66_CC06, S1A_IW_SLC__1SDV_20220302T135216_20220302T135244_042143_05057E_E65B, S1A_IW_SLC__1SDV_20220218T135216_20220218T135244_041968_04FF7A_81E6, S1A_IW_SLC__1SDV_20220206T135216_20220206T135244_041793_04F965_0E4C, S1A_IW_SLC__1SDV_20220125T135217_20220125T135245_041618_04F361_0830, S1A_IW_SLC__1SDV_20220113T135218_20220113T135245_041443_04ED72_18C1, S1A_IW_SLC__1SDV_20220101T135218_20220101T135246_041268_04E7A6_68E0, S1A_IW_SLC__1SDV_20211220T135219_20211220T135245_041093_04E1C6_848E, S1A_IW_SLC__1SDV_20211208T135219_20211208T135246_040918_04DBF1_1DA5, S1A_IW_SLC__1SDV_20211126T135220_20211126T135247_040743_04D5D8_5947, S1A_IW_SLC__1SDV_20211114T135220_20211114T135247_040568_04CFD7_9A78, S1A_IW_SLC__1SDV_20211102T135220_20211102T135247_040393_04C9B8_DF6E, S1A_IW_SLC__1SDV_20211021T135220_20211021T135248_040218_04C3A1_FE38, S1A_IW_SLC__1SDV_20211009T135220_20211009T135248_040043_04BD89_8315, S1A_IW_SLC__1SDV_20210927T135220_20210927T135248_039868_04B77E_B3D4, S1A_IW_SLC__1SDV_20210915T135220_20210915T135247_039693_04B182_0E6B, S1A_IW_SLC__1SDV_20210903T135219_20210903T135247_039518_04AB89_2967, S1A_IW_SLC__1SDV_20210822T135219_20210822T135247_039343_04A583_FF59, S1A_IW_SLC__1SDV_20210810T135218_20210810T135246_039168_049F83_2467, S1A_IW_SLC__1SDV_20210729T135217_20210729T135245_038993_0499C7_A9AF, S1A_IW_SLC__1SDV_20210717T135217_20210717T135245_038818_049496_AB3A, S1A_IW_SLC__1SDV_20210705T135216_20210705T135244_038643_048F59_5277, S1A_IW_SLC__1SDV_20210623T135215_20210623T135243_038468_048A0E_E1A6, S1A_IW_SLC__1SDV_20210611T135215_20210611T135242_038293_0484D8_031A, S1A_IW_SLC__1SDV_20210530T135214_20210530T135242_038118_047FAA_8039, S1A_IW_SLC__1SDV_20210518T135213_20210518T135241_037943_047A68_B435, S1A_IW_SLC__1SDV_20210506T135212_20210506T135240_037768_047520_4CBD, S1A_IW_SLC__1SDV_20210424T135212_20210424T135240_037593_046F1A_CE6E, S1A_IW_SLC__1SDV_20210412T135211_20210412T135239_037418_046911_1D69, S1A_IW_SLC__1SDV_20210331T135211_20210331T135239_037243_046307_955B, S1A_IW_SLC__1SDV_20210319T135211_20210319T135239_037068_045CFB_2231, S1A_IW_SLC__1SDV_20210307T135211_20210307T135238_036893_0456E2_39EB, S1A_IW_SLC__1SDV_20210223T135211_20210223T135239_036718_0450C6_AC0D, S1A_IW_SLC__1SDV_20210211T135211_20210211T135239_036543_044AAA_C439, S1A_IW_SLC__1SDV_20210130T135211_20210130T135239_036368_04449D_7556, S1A_IW_SLC__1SDV_20210118T135212_20210118T135239_036193_043E88_4D05, S1A_IW_SLC__1SDV_20210106T135212_20210106T135240_036018_043864_B5AF, S1A_IW_SLC__1SDV_20201225T135213_20201225T135241_035843_043247_1A2F, S1A_IW_SLC__1SDV_20201213T135213_20201213T135241_035668_042C40_E729, S1A_IW_SLC__1SDV_20201201T135214_20201201T135241_035493_042645_2546, S1A_IW_SLC__1SDV_20201119T135214_20201119T135241_035318_04202F_B1E4, S1A_IW_SLC__1SDV_20201107T135214_20201107T135242_035143_041A16_194F, S1A_IW_SLC__1SDV_20201026T135215_20201026T135243_034968_04140D_246D, S1A_IW_SLC__1SDV_20201014T135215_20201014T135243_034793_040E09_F353, S1A_IW_SLC__1SDV_20201002T135214_20201002T135242_034618_0407ED_E4BB, S1A_IW_SLC__1SDV_20200920T135214_20200920T135242_034443_0401CC_A728, S1A_IW_SLC__1SDV_20200908T135214_20200908T135241_034268_03FB90_715E, S1A_IW_SLC__1SDV_20200827T135213_20200827T135241_034093_03F566_5109, S1A_IW_SLC__1SDV_20200815T135212_20200815T135240_033918_03EF3D_7B6D, S1A_IW_SLC__1SDV_20200803T135212_20200803T135240_033743_03E935_635C, S1A_IW_SLC__1SDV_20200722T135211_20200722T135239_033568_03E3DD_83F4, S1A_IW_SLC__1SDV_20200710T135210_20200710T135238_033393_03DE7E_FE4E, S1A_IW_SLC__1SDV_20200628T135210_20200628T135237_033218_03D930_80B6, S1A_IW_SLC__1SDV_20200616T135209_20200616T135237_033043_03D3DF_1965, S1A_IW_SLC__1SDV_20200604T135208_20200604T135236_032868_03CE9E_9E2F, S1A_IW_SLC__1SDV_20200523T135208_20200523T135235_032693_03C96E_E21C, S1A_IW_SLC__1SDV_20200511T135207_20200511T135235_032518_03C421_C14D, S1A_IW_SLC__1SDV_20200429T135206_20200429T135234_032343_03BE57_32C8, S1A_IW_SLC__1SDV_20200417T135206_20200417T135234_032168_03B834_43BD, S1A_IW_SLC__1SDV_20200405T135205_20200405T135232_031993_03B205_C408, S1A_IW_SLC__1SDV_20200324T135205_20200324T135233_031818_03ABE4_0714, S1A_IW_SLC__1SDV_20200312T135205_20200312T135232_031643_03A5B4_F5F9, S1A_IW_SLC__1SDV_20200217T135205_20200217T135232_031293_03999D_BF2E, S1A_IW_SLC__1SDV_20200205T135205_20200205T135233_031118_03938F_554F, S1A_IW_SLC__1SDV_20200124T135205_20200124T135233_030943_038D6F_1F13, S1A_IW_SLC__1SDV_20200112T135206_20200112T135234_030768_03874B_C235, S1A_IW_SLC__1SDV_20191231T135206_20191231T135234_030593_03813A_D336, S1A_IW_SLC__1SDV_20191219T135207_20191219T135235_030418_037B2D_0DB0, S1A_IW_SLC__1SDV_20191207T135207_20191207T135235_030243_037521_659F, S1A_IW_SLC__1SDV_20191125T135208_20191125T135236_030068_036F1E_A8EE, S1A_IW_SLC__1SDV_20191113T135208_20191113T135236_029893_03690D_70EA, S1A_IW_SLC__1SDV_20191101T135208_20191101T135236_029718_0362E9_8510, S1A_IW_SLC__1SSV_20160719T135144_20160719T135211_012218_012F7E_D146, S1A_IW_SLC__1SSV_20150327T135132_20150327T135209_005218_00696E_A70D, S1A_IW_SLC__1SSV_20150303T135132_20150303T135208_004868_00610C_BF80, S1A_IW_SLC__1SSV_20150126T135132_20150126T135159_004343_0054C0_18DA, S1A_IW_SLC__1SSV_20150102T135133_20150102T135158_003993_004CED_E746, S1A_IW_SLC__1SSV_20141209T135133_20141209T135204_003643_00450B_D085, S1A_IW_SLC__1SSV_20141115T135134_20141115T135211_003293_003D08_1F12

### Share Results

- [ ] Google Earth Engine (GEE)
- [ ] NASA Distributed Active Archive Centers (DAAC) User Acceptance Testing (UAT)

### Additional Notes

Scenes for static file processing:
S1A_IW_SLC__1SSV_20141115T135134_20141115T135211_003293_003D08_1F12, S1A_IW_SLC__1SSV_20141209T135133_20141209T135204_003643_00450B_D085, S1A_IW_SLC__1SSV_20141209T135133_20141209T135204_003643_00450B_D085

**Comment by niarenaw** [comment]
Completed in [[Processing Request]: R2 Final CalVal processing#13](https://github.com/nasa/opera-sds/issues/13)
