### ISSUE TITLE
[Processing Request]: WV/VA, Ascending, High Priority

### ISSUE THREAD

**Issue by Alex-Lewandowski** [nasa/opera-sds#30]
### Venue

PST

### Product

RTC-S1

### SAS Version

latest

### SDS Version

latest

### Input Data

S1A_IW_SLC__1SDV_20210106T231515_20210106T231542_036024_043894_134D, S1A_IW_SLC__1SDV_20210130T231514_20210130T231541_036374_0444CC_3BF7, S1A_IW_SLC__1SDV_20210223T231514_20210223T231541_036724_0450F6_C5A2, S1A_IW_SLC__1SDV_20210319T231514_20210319T231541_037074_045D2D_5154, S1A_IW_SLC__1SDV_20210412T231515_20210412T231541_037424_046941_8AE8, S1A_IW_SLC__1SDV_20210506T231516_20210506T231542_037774_047550_C4CD, S1A_IW_SLC__1SDV_20210530T231517_20210530T231544_038124_047FD9_2853, S1A_IW_SLC__1SDV_20210623T231518_20210623T231545_038474_048A3E_D089, S1A_IW_SLC__1SDV_20210717T231520_20210717T231547_038824_0494C6_E579, S1A_IW_SLC__1SDV_20210822T231522_20210822T231549_039349_04A5B2_54F3, S1A_IW_SLC__1SDV_20210915T231523_20210915T231550_039699_04B1B3_B89B, S1A_IW_SLC__1SDV_20211009T231523_20211009T231550_040049_04BDB9_99CD, S1A_IW_SLC__1SDV_20211102T231523_20211102T231550_040399_04C9EA_AF49, S1A_IW_SLC__1SDV_20211126T231523_20211126T231550_040749_04D608_6DC5, S1A_IW_SLC__1SDV_20211220T231522_20211220T231549_041099_04E1F9_9F4A

### Share Results

- [ ] Google Earth Engine (GEE)
- [ ] NASA Distributed Active Archive Centers (DAAC) User Acceptance Testing (UAT)

### Additional Notes

Scenes for static file processing:
S1A_IW_SLC__1SDV_20210106T231515_20210106T231542_036024_043894_134D

**Comment by niarenaw** [comment]
outputs: [issue30_rtc.txt](https://github.com/nasa/opera-sds/files/12877059/issue30_rtc.txt)
