### ISSUE TITLE
[Processing Request]: CSLC-S1 for New Mexico and Alaska 

### ISSUE THREAD

**Issue by gracebato** [nasa/opera-sds#33]
### Venue

PST

### Product

CSLC-S1

### Input Data

[A065_ALASKA_additional.txt](https://github.com/nasa/opera-sds/files/12860053/A065_ALASKA_additional.txt)
[D131_ALASKA_additional.txt](https://github.com/nasa/opera-sds/files/12860054/D131_ALASKA_additional.txt)
[D056_NewMexico.txt](https://github.com/nasa/opera-sds/files/12860055/D056_NewMexico.txt)
[A151_NewMexico.txt](https://github.com/nasa/opera-sds/files/12860056/A151_NewMexico.txt)

### Share Results

- [ ] Google Earth Engine (GEE)
- [ ] NASA Distributed Active Archive Centers (DAAC) User Acceptance Testing (UAT)

### Additional Notes
This is a request for product version v1.0 (before Az FM rate correction).
Please include relevant static layers production for this request.

**Comment by niarenaw** [comment]
Processing completed -- s3 manifest below:

[request_31_32_static_CSLC.txt](https://github.com/nasa/opera-sds/files/12877034/request_31_32_static_CSLC.txt)
[request_31_CSLC.txt](https://github.com/nasa/opera-sds/files/12877036/request_31_CSLC.txt)
