### ISSUE TITLE
[Processing Request]: Failed Granule for RTC Validation

### ISSUE THREAD

**Issue by cmarshak** [nasa/opera-sds#34]
### Venue

PST

### Product

RTC-S1

### SAS Version

1.0.1 (latest)

### Input Data

S1A_IW_SLC__1SDV_20230114T161231_20230114T161258_046782_059BD6_D15F

### Share Results

- [ ] Google Earth Engine (GEE)
- [ ] NASA Distributed Active Archive Centers (DAAC) User Acceptance Testing (UAT)

### Additional Notes

Can you regenerate the RTC products from the input granule: [S1A_IW_SLC__1SDV_20230114T161231_20230114T161258_046782_059BD6_D15F](https://search.asf.alaska.edu/#/?searchType=List%20Search&searchList=S1A_IW_SLC__1SDV_20230114T161231_20230114T161258_046782_059BD6_D15F&resultsLoaded=true)
 
It is referenced here too: https://github.com/OPERA-Cal-Val/calval-RTC/pull/10
 
Please confirm that it does not fail. It might have failed due to previous systems, but we need for final validation delivery.

**Comment by niarenaw** [comment]
The SAS failed on this granules and the issue does not appear to be transient.

**Comment by cmarshak** [comment]
Ok - I guess I can close this issue - I am assuming other people are aware of this software issue.

Tagging @alhandwerger.
