### ISSUE TITLE
[Processing Request]: Process Historical RTCs for DSWx-SAR

### ISSUE THREAD

**Issue by cmarshak** [nasa/opera-sds#36]
### Venue

PST

### Product

RTC-S1

### SAS Version

latest

### SDS Version

latest

### Input Data

S1A_IW_SLC__1SDV_20210902T223854_20210902T223921_039509_04AB30_6369
S1A_IW_SLC__1SDV_20210930T093428_20210930T093455_039909_04B8EE_00E0
S1B_IW_SLC__1SDV_20211005T034929_20211005T034956_028995_0375C0_AA59
S1A_IW_SLC__1SDV_20211003T030717_20211003T030745_039949_04BA4B_A7EB
S1B_IW_SLC__1SDV_20211002T223954_20211002T224021_028963_0374D0_A66C
S1A_IW_SLC__1SDV_20211006T084622_20211006T084641_039996_04BBFB_1926
S1B_IW_SLC__1SDV_20211006T093926_20211006T093954_029013_037654_9260
S1B_IW_SLC__1SDV_20211002T225928_20211002T225955_028963_0374D1_06C9
S1B_IW_SLC__1SDV_20211012T115332_20211012T115359_029102_037901_E1B9
S1A_IW_SLC__1SDV_20210930T183712_20210930T183739_039915_04B927_38FB
S1B_IW_SLC__1SDV_20211010T203632_20211010T203659_029078_03784D_C01F
S1B_IW_SLC__1SDV_20211013T231248_20211013T231315_029123_0379A8_5944
S1B_IW_SLC__1SDV_20211017T013542_20211017T013609_029169_037B1D_3867
S1B_IW_SLC__1SDV_20211022T014532_20211022T014559_029242_037D5F_7ED3
S1B_IW_SLC__1SDV_20211021T010807_20211021T010835_029227_037CEE_32F0
S1A_IW_SLC__1SDV_20211027T190207_20211027T190234_040309_04C6D2_D00B
S1B_IW_SLC__1SDV_20211102T213211_20211102T213238_029414_0382AD_C28E
S1B_IW_SLC__1SDV_20211030T010133_20211030T010200_029358_0380F8_8F18
S1B_IW_SLC__1SDV_20211103T090527_20211103T090554_029421_0382E7_400E
S1B_IW_SLC__1SDV_20211011T043918_20211011T043945_029083_03786C_A6CD
S1A_IW_SLC__1SDV_20210927T100304_20210927T100331_039866_04B76B_2C51
S1B_IW_SLC__1SDV_20210929T024452_20210929T024518_028907_037325_8D78
S1A_IW_SLC__1SDV_20210929T212300_20210929T212327_039902_04B8B6_D791
S1A_IW_SLC__1SDV_20210904T222218_20210904T222245_039538_04AC38_0F48
S1A_IW_SLC__1SDV_20210907T172712_20210907T172739_039578_04ADAE_65C7
S1B_IW_SLC__1SDV_20210906T175448_20210906T175516_028581_036928_0974
S1B_IW_SLC__1SDV_20210908T200340_20210908T200409_028611_036A1F_61D5
S1B_IW_SLC__1SDV_20210908T200315_20210908T200342_028611_036A1F_28A5
S1B_IW_SLC__1SDV_20210906T213322_20210906T213349_028583_036939_DCDC
S1B_IW_SLC__1SDV_20210909T234014_20210909T234041_028628_036AAA_91C4
S1A_IW_SLC__1SDV_20210914T173107_20210914T173134_039681_04B127_2447
S1B_IW_SLC__1SDV_20210914T164916_20210914T164943_028697_036CB4_F3E2
S1B_IW_SLC__1SDV_20210914T053949_20210914T054016_028690_036C77_69DB
S1A_IW_SLC__1SDV_20210910T203331_20210910T203358_039624_04AF36_CDD3
S1B_IW_SLC__1SDV_20210916T014005_20210916T014033_028717_036D52_F3D7
S1B_IW_SLC__1SDV_20210915T010037_20210915T010104_028702_036CD8_8EC6
S1A_IW_SLC__1SDV_20210915T202446_20210915T202516_039697_04B1A6_8B44
S1A_IW_SLC__1SDV_20210915T214008_20210915T214035_039698_04B1AD_1632
S1B_IW_SLC__1SDV_20210916T230841_20210916T230909_028730_036DBD_6669
S1B_IW_SLC__1SDV_20210925T011803_20210925T011830_028848_037153_D72D
S1A_IW_SLC__1SDV_20210924T201704_20210924T201731_039828_04B61E_58AE
S1A_IW_SLC__1SDV_20210924T034729_20210924T034756_039818_04B5C3_4500
S1B_IW_SLC__1SDV_20211028T095649_20211028T095716_029334_038044_6F2A
S1A_IW_SLC__1SDV_20211025T235550_20211025T235620_040282_04C5E8_B6DE

### Share Results

- [ ] Google Earth Engine (GEE)
- [ ] NASA Distributed Active Archive Centers (DAAC) User Acceptance Testing (UAT)

**Comment by cmarshak** [comment]
**Note**: I have not checked in advance if these SLCs are already there - there is a good chance they are. Please let me know when they are completed.

**Comment by cmarshak** [comment]
When convenient, please provide ETA on delivery as orbit download issue is causing a delay. Thank you.

I will need ES access on one SDS deployment for easy organization of final products.

**Comment by niarenaw** [comment]
@cmarshak Hoping to have this done by EOW -- PST is to be redeployed tomorrow and I can start then.

**Comment by cmarshak** [comment]
Thanks, Nick! 

I will likely continue to request SLCs to be processed in the coming weeks. I don't think this should be as much of delay because there is not expected redeployment (i.e. updating the orbit API). Let me know.

**Comment by niarenaw** [comment]
@cmarshak processing is complete - let me know if you need a list of output products or anything.

**Comment by cmarshak** [comment]
Thanks, Nick!
