### ISSUE TITLE
[Processing Request]: Historical DSWx-S1 Request in Florida

### ISSUE THREAD

**Issue by cmarshak** [nasa/opera-sds#48]
### Venue

PST

### Product

DSWx-S1

### Input Data

Here is a list of the input granules used along with the MGRS tiles: https://github.com/OPERA-Cal-Val/DSWx-Validation-Experiments/blob/main/marshak/dswx-s1-organization/jwjones_eden_request.csv

### Share Results

- [ ] Google Earth Engine (GEE)
- [ ] NASA Distributed Active Archive Centers (DAAC) User Acceptance Testing (UAT)

### Additional Notes

For John Jones

**Comment by niarenaw** [comment]
Products should be available. Please let me know if any output sheets/lists are needed.

**Comment by niarenaw** [comment]
Will reprocess with final DSWx-S1 release for IV validation.

**Comment by niarenaw** [comment]
Output products from 2024-08 processing campaing on PST S3:
[request-48-outputs.txt](https://github.com/user-attachments/files/16853446/request-48-outputs.txt)
